- rinad/etc/ipcmanager.conf.in
- rinad/src/common/rina-configuration.cc
- rinad/src/common/rina-configuration.h
- rinad/src/ipcm/configuration.cc
- rinad/src/ipcm/ipcm.cc
- tests/conf/ipcmanager.conf-appoverdummy
- tests/conf/ipcmanager.conf-appovereth
- tests/conf/ipcmanager.conf-appovershimhv
- tests/conf/ipcmanager.conf-appovertcpudp
- tests/conf/ipcmanager.conf-normaloverdummy
- tests/conf/ipcmanager.conf-normalovereth1
- tests/conf/ipcmanager.conf-normalovereth2
- tests/conf/ipcmanager.conf-normalovereth2cubes
- tests/conf/ipcmanager.conf-normalovernormalovereth1
- tests/conf/ipcmanager.conf-normalovernormalovereth2
- tests/conf/ipcmanager.conf-normalovershimhv1
- tests/conf/ipcmanager.conf-normalovershimhv2
- tests/conf/ipcmanager.conf-normalovertcpudp1
- tests/conf/ipcmanager.conf-normalovertcpudp2
> Pristine 1.1 468

- linux/net/rina/pci.c
- linux/net/rina/pci.h
- linux/net/rina/rmt.c
- linux/net/rina/serdes.c
This commit just updates the bitcodes of the PDU types as reflected in the last EFCP specs
> PDU type bitcodes updated to last specs

- librina/include/librina/common.h
- librina/src/cdap-impl.cc
- librina/src/common.cc
- librina/src/core.cc
- rina-tools/src/rina-cdap-echo/Makefile.am
- rina-tools/src/rina-cdap-echo/cdap-echo-application.cc
- rina-tools/src/rina-cdap-echo/cdap-echo-application.h
- rina-tools/src/rina-cdap-echo/cdap-echo-client.cc
- rina-tools/src/rina-cdap-echo/cdap-echo-client.h
- rina-tools/src/rina-cdap-echo/cdap-echo-server.cc
- rina-tools/src/rina-cdap-echo/cdap-echo-server.h
- rina-tools/src/rina-cdap-echo/main.cc
- rinad/src/ipcp/rib-daemon.cc
Still some valgrind errors while closing app but these are librina problems so I will go over them when I have free time. I also reformated
> Pristine 1.1 cdap app

- linux/net/rina/efcp.c
Wrong check in efcp_container_unbind_user_ipcp
> Fixes #502 bug: unable to handle kernel paging request at 6b6b6ba3 when N-1 port is removed

- librina/include/librina/exceptions.h
- librina/src/exceptions.cc
- rina-tools/src/rina-cdap-echo/main.cc
- rina-tools/src/rina-echo-time/main.cc
- rinad/src/common/encoder.cc
- rinad/src/common/event-loop.cc
- rinad/src/ipcm/addons/console.cc
- rinad/src/ipcm/app-handlers.cc
- rinad/src/ipcm/ipcm.cc
- rinad/src/ipcm/ipcp.cc
- rinad/src/ipcp/components.cc
- rinad/src/ipcp/default-flow-allocator-ps.cc
- rinad/src/ipcp/default-namespace-manager-ps.cc
- rinad/src/ipcp/default-resource-allocator-ps.cc
- rinad/src/ipcp/enrollment-task.cc
- rinad/src/ipcp/flow-allocator.cc
- rinad/src/ipcp/flow-allocator.h
- rinad/src/ipcp/ipc-process.cc
- rinad/src/ipcp/link-state-routing-ps.cc
- rinad/src/ipcp/main.cc
- rinad/src/ipcp/namespace-manager.cc
- rinad/src/ipcp/resource-allocator.cc
- rinad/src/ipcp/rib-daemon.cc
- rinad/src/ipcp/test-link-state-routing.cc
Closes #383.
This changes touches librina and rinad so that the Exception class is properly defined in the rina namespace defined by librina.
> librina: put Exception class in namespace rina

- rinad/src/ipcm/ipcm.h
- rinad/src/ipcm/ipcp-handlers.cc
Fix #520: double completion of transaction.
> Fix #520: double completion of transaction

- librina/src/cdap-impl.cc
- librina/src/cdap.cc
- rinad/src/ipcm/ipcm.h
- rinad/src/ipcp/components.cc
- rinad/src/ipcp/components.h
- rinad/src/ipcp/default-security-manager-ps.cc
- rinad/src/ipcp/link-state-routing-ps.cc
- rinad/src/ipcp/plugins/security-manager-passwd.cc
- rinad/src/ipcp/resource-allocator.cc
This pull req fixes some errors thrown by clang/clang++
We should try to automate building in travis for multiple compilers, and compiler versions.
> Fixing numerous clang errors and warnings

- rinad/src/ipcm/addons/console.cc
- rinad/src/ipcm/policies-handlers.cc
- rinad/src/ipcp/plugins/Makefile.am
Due to latest code refactors (IPCM and DAF classes).
> Fixed problems in the makefile of sm-passwd plugin and IPCM plugin-load

- librina/src/concurrency.cc
> Remove annoying mutex/rwlock/cond_var DBG output

- librina/include/librina/common.h
- librina/include/librina/ipc-api.h
- librina/include/librina/ipc-process.h
- librina/include/librina/irm.h
- librina/src/common.cc
- librina/src/ipc-api.cc
- librina/src/ipc-process.cc
- librina/src/irm.cc
- librina/test/test-01.cc
- librina/wrap/librina.i
- rina-tools/src/rina-cdap-echo/cdap-echo-client.cc
- rina-tools/src/rina-cdap-echo/cdap-echo-client.h
- rina-tools/src/rina-cdap-echo/cdap-echo-server.cc
- rina-tools/src/rina-cdap-echo/cdap-echo-server.h
- rina-tools/src/rina-echo-time/client.cc
- rina-tools/src/rina-echo-time/client.h
- rina-tools/src/rina-echo-time/server.cc
- rina-tools/src/rina-echo-time/server.h
- rinad/src/ipcp/resource-allocator.cc
Summary of changes (related do issue #556):
* Got rid of Flow * object
* Moved  read/write to IPCManager class
* Improved locking of rina-ipc-api
* Updated IPCP and applications in rina-tools
> Pristine 1.2 #556 Fixes to rina-ipc-api

- librina/include/librina/cdap.h
- librina/include/librina/rib.h
- librina/src/cdap-impl.cc
- librina/src/cdap-impl.h
- librina/src/cdap.cc
- librina/src/rib.cc
- rinad/src/ipcp/components.h
- rinad/src/ipcp/flow-allocator.cc
- rinad/src/ipcp/flow-allocator.h
- rinad/src/ipcp/rib-daemon.cc
Work on #560 
* Fixed RIB Daemon
* Fixed Flow Allocator
> Fix #560 : Stop using CDAP sessions when sending CDAP message to address

- rinad/src/ipcm/main.cc
- rinad/src/ipcp/main.cc
Remove useless WANT_PARACHUTE knob and install always the SIGSEGV signal
handler.
> Remove WANT_PARACHUTE and install SIGSEGV handler

- librina/include/librina/cdap_rib_structures.h
- librina/src/cdap_v2.cc
Fioxed a librina swigg issue for MAD-Manager integration
> Changes in the serialized object for better swog bindings

- linux/net/rina/kfa.c
This fixes the problem identified at https://github.com/IRATI/stack/issues/593 related with kfa deallocation of flows when triggered by the reception of a pdu in the underlaying EFCP. When it is not possible to destroy the kfa's flow due to pending operations, the port is set to DEALLOCATED but the deletion task and the awakening of sleeping read syscalls is deferred to a dedicated workqueue (process context).
> Fix for bug #593  in pristin1.3

- rinad/src/ipcm/dif-template-manager.cc
Fixes #600 https://github.com/IRATI/stack/issues/600
> ipcm: dif-template-manger: filter by file name suffix

- rinad/src/ipcp/plugins/default/test-routing.cc
- rinad/src/ipcp/test-encoders.cc
This makes compilation of tests successful again.
Compilation was broken by past pull requests.
> rinad: ipcp: update make check tests

- linux/net/rina/ipcps/normal-ipcp.c
Fixed bad locking in the normal ipcp in connection creation.
> Pristine 1.2 #612 Fixed bug in creation of EFCP instances

- rinad/src/ipcp/ipc-process.cc
Little fix for the log string.
> rinad: ipcp: SDK: improve logging

- MAINTAINERS
- check_maintainers.py
This commit adds MAINTAINERS file, with an initial assignment
of the maintainer duties over the base code.
The commit also contains check_maintainers.py script that SHALL
be checked against the code base for new patches/pull-requests.
To be upstreamed integration-1.2 -> master-1.2
> Adding MAINTAINERS file and check_maintainers.py

- linux/net/rina/rmt.c
Fixed coding style issues reported by @sandervrijders (too long lines, wrong placing of parentheses)
Mainainer: @miqueltarzan
> fixed coding style issues, fix #650

- librina/include/librina/ipc-api.h
- librina/include/librina/ipc-manager.h
- librina/src/ipc-api.cc
- librina/src/ipc-manager.cc
- librina/src/netlink-messages.h
- librina/src/netlink-parsers.cc
- librina/src/netlink-parsers.h
- librina/src/syscalls-wrappers.cc
- librina/wrap/librina.i
- linux/net/rina/default.c
- linux/net/rina/ipcp-instances.h
- linux/net/rina/ipcps/shim-eth-vlan.c
- linux/net/rina/ipcps/shim-hv.c
- linux/net/rina/ipcps/shim-tcp-udp.c
- linux/net/rina/kipcm.c
- linux/net/rina/kipcm.h
- linux/net/rina/rnl-utils.h
- rina-tools/src/rina-cdap-echo/cdap-echo-client.cc
- rina-tools/src/rina-cdap-echo/cdap-echo-server.cc
- rina-tools/src/rina-echo-time/et-client.cc
- rinad/src/ipcm/addons/console.cc
- rinad/src/ipcm/addons/ma/ribs/ipc_processes_obj.cc
- rinad/src/ipcm/app-handlers.cc
- rinad/src/ipcm/ipcm.cc
- rinad/src/ipcm/ipcm.h
- rinad/src/ipcm/ipcp.cc
- rinad/src/ipcm/ipcp.h
* Fixed wrong kfa_flow_create calls
* Removed TryAgainException and updated apps
* Fixed wrong specification of blocking flow behavior when registering an application
> Several fixes in non-blocking flows behaviour

- MAINTAINERS
- plugins/dummy/Makefile
- plugins/dummy/dummy-plugin-ps.c
- plugins/dummy/pft-ps-dummy.c
- plugins/red/Makefile
This patch fixes compilation problems with the non-default kernel plugins and adds support for the "make install" target.
> Fix kernel plugins

- linux/net/rina/rmt.c
Simple locking fixing. @miqueltarzan is the mainteiner of the file, but I would ask @edugrasa and @olichtne to check I did not do anything wrong there.
> Bad locking in rmt.c when retrieving N-1 Port

- librina/configure.ac
- rina-tools/configure.ac
- rinad/configure.ac
Added AS_IF checks and error messages for configuration of librina, rinad, rina-tools.
fixes #709
> Added AS_IF to check that actually the binaries are found

- linux/net/rina/rmt.c
This solves #716 
the interrupt coming from the NIC when receiving a frame
can take the lock in the n1_ports/n1_port structs in the rmt
when trying to enable/disable it. The same operation can be concurrently
originated by a write syscall from user-space. irqsave added to the lock ops.
Maintainer @miqueltarzan
> pristine-1.3: fix softlockup in enable/disable port 

- linux/net/rina/syscalls.c
linux:
syscalls.c : refactored to comply with kernel coding style
maintainer: @lbergesio
> Refactored linux syscall.c

- linux/net/rina/kfa.c
- linux/net/rina/kfa.h
kfa.[c/h] : refactored code to comply with kernel guidelines
maintainer: @miqueltarzan
> Refactor of kernel flow allocator

- linux/net/rina/dt-utils.c
- linux/net/rina/ipcps/normal-ipcp.c
- linux/net/rina/rmt-ps-common.c
- linux/net/rina/rmt-ps-common.h
- linux/net/rina/rmt-ps-default.c
- linux/net/rina/rmt-ps.h
- linux/net/rina/rmt.c
- linux/net/rina/rmt.h
This refactors the RMT. Fixes several bad locking and possible memory leaks. All files related to RMT now also pass the check with checkpatch.pl. Henceforth any RMT changes should be checked with it as well. 
Maintainer: @miqueltarzan for everything RMT related, @lbergesio for dt-utils.c
> Refactoring of the RMT component in the kernel

- librina/include/librina/cdap_v2.h
- librina/src/cdap_v2.cc
- librina/wrap/librina.i
- rinad/src/ipcm/addons/ma/ribs/ipcp_obj.cc
Java manager working with the stack and 1 node. Added missing exceptions and a missing opcode from the MAD. Manager can be found here https://github.com/bernatgaston/manager
ack @edugrasa
> Pristine 1.3 manager working

- rinad/src/ipcm/dif-template-manager.cc
- rinad/src/ipcm/ipcm.cc
Fixes #656 
Maintainers: @vmaffione
> rinad: ipcm: use correct folder in Template Manager

- plugins/multipath/pff-ps-multipath.c
Merge latest pristine-1.3 into pristine-1.4
> Pristine 1.4

- librina/include/librina/cdap_v2.h
- librina/src/cdap_v2.cc
> Free users of CDAP Provider from having to generate invoke_ids if they don't want to do so

- plugins/example-sm-plugin/sm-example.cc
Compilation was broken by #816.
> plugins: fix compilation of user-space template plugin

- rinad/src/ipcp/plugins/default/test-routing.cc
> Tests of routing default plugin fixed

- librina/src/configuration.cc
> Mcr bug840

- linux/net/rina/ipcps/shim-eth-utils.c
Take and release rtnl_mutex before adding/removing qdiscs. Fix #847 
I've tested and the logs are gone, shim-eth continues working.
@kewinrausch or @lbergesio could you ACK this one?
> kernel: shim-eth-qdisc-utils: take and release rtnl_mutex 

- plugins/multipath/pff-ps-multipath.c
Fixes multipath pff policy null pointer handling
> fixes #846

- linux/net/rina/ipcps/shim-eth-vlan-core.c
> kernel: shim-eth-vlan: fix #849, fix #749

- linux/net/rina/ipcps/shim-tcp-udp.c
> kernel: shim-tcp-udp: improve cleanup, fix #575, fix #444

- linux/net/rina/ipcps/shim-eth-utils.c
> rina: shim-eth-utils: fix #753, related to qdisc cleanup

- rinad/src/ipcm/ipcm.cc
> Check te pointer to the ipcp before accessing it

- rinad/etc/Makefile.am
- rinad/etc/ipcmanager.conf.in
- rinad/src/common/rina-configuration.cc
- rinad/src/common/rina-configuration.h
- rinad/src/ipcm/Makefile.am
- rinad/src/ipcm/addon.cc
- rinad/src/ipcm/addons/console.cc
- rinad/src/ipcm/addons/console.h
- rinad/src/ipcm/configuration.cc
- tests/conf/ipcmanager.conf-appovereth
- tests/conf/ipcmanager.conf-appovershimhv
- tests/conf/ipcmanager.conf-appovertcpudp
- tests/conf/ipcmanager.conf-mad
- tests/conf/ipcmanager.conf-normalovereth1
- tests/conf/ipcmanager.conf-normalovereth2
- tests/conf/ipcmanager.conf-normalovernormalovereth1
- tests/conf/ipcmanager.conf-normalovernormalovereth2
- tests/conf/ipcmanager.conf-normalovershimhv1
- tests/conf/ipcmanager.conf-normalovershimhv2
- tests/conf/ipcmanager.conf-normalovertcpudp1
- tests/conf/ipcmanager.conf-normalovertcpudp2
- tests/conf/vm-to-vm/ipcmanager.conf-pm
- tests/conf/vm-to-vm/ipcmanager.conf-vm.1
- tests/conf/vm-to-vm/ipcmanager.conf-vm.2
- tests/conf/vpn/ipcmanager.conf-pm.i2cat
- tests/conf/vpn/ipcmanager.conf-pm.nxw
- tests/conf/vpn/ipcmanager.conf-vm.i2cat
- tests/conf/vpn/ipcmanager.conf-vm.nxw
The 3 commits are atomic, in that we could only merge the first, or the first 2.
I implemented the 3rd one mainly for security reasons. Then, I'd have to update the wiki to use "socat" instead of "telnet".
> IPCM: console improvements

- linux/net/rina/rinarp/arp826-core.c
- linux/net/rina/rinarp/arp826-rxtx.c
- linux/net/rina/rinarp/arp826-tables.c
- linux/net/rina/rinarp/arp826-tables.h
These two commits fix two issues we had with the shim-eth-vlan, and were discussed during the developer's meeting.
@vmaffione Could you give it a try to see if they are resolved?
> Shim-eth-vlan bugfixes

- linux/net/rina/ipcps/shim-tcp-udp.c
Several fixes to the shim DIF over TCP and UDP:
* Fix locking to avoid the problems reported by #424, #436, #440 
* Not sure why it was happening, but #886 seems to be fixed also (at least I could not reproduce it)
* Limited the size of the "outgoing SDUs" queue, which was unbounded and could make the system to run out of kernel memory and crash (happened to me several times). Also added vertical flow control to disable/enable the ports when the queue transitions from not full to full and viceversa.
Maintainers: @sandervrijders. @jmuchemb  could you also give it a try to see if #886 is addressed?
> Pristine 1.5 shim TCP, UDP fixes

- rinad/Makefile.am
> rinad: create log directory at install

- linux/net/rina/ipcps/shim-tcp-udp.c
Updated parse_* functions and added support for IPv6
> shim-tcp-udp: add support for IPv6

- linux/net/rina/ipcps/shim-tcp-udp.c
> kernel: shim-tcp-udp improvements

- librina/include/librina/application.h
- librina/src/application.cc
- librina/src/rib_v2.cc
- rinad/src/ipcm/addons/ma/ribf.cc
- rinad/src/ipcm/ipcm.cc
- rinad/src/ipcp/components.h
- rinad/src/ipcp/enrollment-task.cc
- rinad/src/ipcp/enrollment-task.h
- rinad/src/ipcp/flow-allocator.cc
- rinad/src/ipcp/flow-allocator.h
- rinad/src/ipcp/ipc-process.cc
- rinad/src/ipcp/namespace-manager.cc
- rinad/src/ipcp/namespace-manager.h
- rinad/src/ipcp/plugins/default/routing-ps.cc
- rinad/src/ipcp/plugins/default/routing-ps.h
- rinad/src/ipcp/resource-allocator.cc
- rinad/src/ipcp/rib-daemon.cc
- rinad/src/ipcp/rib-daemon.h
- rinad/src/ipcp/routing.cc
- rinad/src/ipcp/security-manager.cc
Fixed various segfaults when closing the IPCP + MA.
Fixes #873 
ACK @vmaffione @edugrasa
> IPCP closing

- rinad/src/ipcm/addons/console.cc
> Valgrind fix

- librina/wrap/librina.i
> Fix build of librina due to wrong comment in swig file

- linux/net/rina/dtcp-ps-default.c
- linux/net/rina/dtcp.c
- linux/net/rina/dtp.c
This PR will fix some bugs in the DTP and DTCP. There were some errors in the way PDUs were handled when A>0.
Maintainers: @lbergesio
> kernel: dtp: dtcp: dtcp-ps-default: fix bugs in EFCP

- rinad/src/ipcm/main.cc
Added SIGCHLD handler to IPCM to reap child IPC Process Daemons … (avoid zombies)
Maintainers: @vmaffione
> Added SIGCHLD handler to IPCM

- librina/src/cdap_v2.cc
- rinad/src/ipcm/ipcm.cc
- rinad/src/ipcm/ipcm.h
> Fixed valgrind problems and optimized ipcm closing

- rinad/src/ipcm/ipcm.cc
> Delegation to a shim IPCP not allowed

- librina/src/ipc-process.cc
- rinad/src/ipcp/utils.cc
Two small code fixes that cause compilation warnings.
> Fix compilation gcc6

- plugins/lfa/ps.c
plugins: lfa: more detailed logs for port_up and port_down handlers
> plugins: lfa: more detailed logs for port_up and port_down handlers

- librina/include/librina/rib_v2.h
- librina/src/rib_v2.cc
- rinad/src/ipcm/addons/ma/ribs/ipcp_obj.cc
- rinad/src/ipcm/addons/ma/ribs/ipcp_obj.h
- rinad/src/ipcm/ipcm.cc
- rinad/src/ipcp/flow-allocator.cc
- rinad/src/ipcp/flow-allocator.h
Merge Bernat's and Micheal PR into one. Tested already.
> Pristine 1.5 mad

- librina/src/rib_v2.cc
- rinad/src/ipcm/addon.h
- rinad/src/ipcm/addons/console.cc
- rinad/src/ipcm/addons/console.h
- rinad/src/ipcm/addons/ma/agent.cc
- rinad/src/ipcm/addons/ma/agent.h
- rinad/src/ipcm/addons/ma/confm.cc
- rinad/src/ipcm/addons/ma/flowm.cc
- rinad/src/ipcm/addons/ma/ribf.cc
- rinad/src/ipcm/addons/ma/ribf.h
- rinad/src/ipcm/addons/ma/ribs/ipcp_obj.cc
- rinad/src/ipcm/addons/ma/ribs/ipcp_obj.h
- rinad/src/ipcm/addons/ma/ribs/ribd_v1.cc
- rinad/src/ipcm/ipcm.cc
- rinad/src/ipcm/ipcm.h
- tests/conf/ipcmanager.conf-mad
* show Management Agent info on list-ipcp command
* added query-ma-rib command
* clean code and improve stability of Management Agent
Maintainers: @bernatgaston
> Pristine 1.5 mad improvements

- linux/net/rina/dt-utils.c
kernel: dt-utils: Fix a bug in the way the window was re-opened, since it was done outside of the protection provided by the locking mechanism.
> Pristine 1.5 dt-utils bug

- linux/net/rina/dtcp.c
- linux/net/rina/dtp.c
- linux/net/rina/dtp.h
- linux/net/rina/rds/Kconfig
- linux/net/rina/rds/Makefile
- linux/net/rina/rds/rds.c
- linux/net/rina/rds/rds.h
- linux/net/rina/rds/ringq.c
- linux/net/rina/rds/ringq.h
Refactor of the DTP, with changes in the way the control messages are generated.
maintainer: @lbergesio
> kernel: rds: dtp Add new data structure to implement finite size queues plus a refactor of dtp

- linux/net/rina/ipcp-utils.c
- linux/net/rina/ipcps/normal-ipcp.c
- linux/net/rina/ipcps/shim-tcp-udp.c
- linux/net/rina/kfa.c
- linux/net/rina/rds/robjects.h
- linux/net/rina/sdup.c
The first commit is the most important: it fixes a few memory leaks that were reported by kmemleak.
> kernel: various fixes

- rina-tools/src/common/server.h
- rina-tools/src/common/utils.cc
- rina-tools/src/rina-cdap-echo/cdap-echo-client.cc
- rina-tools/src/rina-cdap-echo/cdap-echo-client.h
- rina-tools/src/rina-cdap-echo/cdap-echo-server.cc
- rina-tools/src/rina-cdap-echo/cdap-echo-server.h
- rina-tools/src/rina-echo-time/et-client.cc
> Fix for issue #1004: Clean compile with -Wall

- misc/code-stats
1) update reference branch to pristine-1.5
2) consider changes in linux/net/rina only, rather than considering all the changes in linux/, which also include kernel upgrades provided by the linux community
> misc: code-stats: update development branch and fix kernel statistics

- librina/src/cdap_v2.cc
> librina: fixed errors in CDAP invoke-id processing

- rinad/src/ipcp/namespace-manager.cc
- rinad/src/ipcp/namespace-manager.h
Merging, required for experiments
> rinad: fixed bug in namespacemanager when detecting lost neighbors

- librina/src/cdap_v2.cc
- rinad/src/ipcp/enrollment-task.cc
- rinad/src/ipcp/enrollment-task.h
- rinad/src/ipcp/plugins/default/enrollment-task-ps.cc
@jmuchemb could you test this one? I think that it should fix all segfaults related to deleting the enrollment state machines ...
> Pristine 1.5 segfault

- rinad/src/ipcm/configuration.cc
- rinad/src/ipcm/configuration.h
- rinad/src/ipcm/dif-allocator.cc
- rinad/src/ipcm/dif-allocator.h
- rinad/src/ipcm/ipcm.cc
- rinad/src/ipcm/ipcp.cc
- rinad/src/ipcm/ipcp.h
And automatically pick the right one. Tested, seems to work ok with no regressions.
@vmaffione could you take a look? Thanks!
> rinad: updated DIF allocator to handle same app registered in many DIFs

- linux/archlinux-install-kernel
An useful script for Archlinux users on IRATI
> kernel: add script to build/install kernel on Archlinux

- librina/include/librina/enrollment.h
- librina/src/ipc-manager.cc
- rinad/src/ipcp/Makefile.am
- rinad/src/ipcp/components.h
- rinad/src/ipcp/enrollment-task.cc
- rinad/src/ipcp/enrollment-task.h
- rinad/src/ipcp/flow-allocator.cc
- rinad/src/ipcp/flow-allocator.h
- rinad/src/ipcp/ipc-process.cc
- rinad/src/ipcp/ipc-process.h
- rinad/src/ipcp/main.cc
- rinad/src/ipcp/normal-ipc-process.cc
Addresses #1038 
@vmaffione, @lbergesio could you take a look?
> Arcfire ipcp factories

- librina/include/librina/cdap_v2.h
- librina/include/librina/security-manager.h
- librina/src/cdap_v2.cc
- librina/src/security-manager.cc
- rina-tools/configure.ac
- rina-tools/src/Makefile.am
- rina-tools/src/key-managers/Makefile.am
- rina-tools/src/key-managers/Makefile.inc
- rina-tools/src/key-managers/ckm.cc
- rina-tools/src/key-managers/ckm.h
- rina-tools/src/key-managers/km-common.cc
- rina-tools/src/key-managers/km-common.h
- rina-tools/src/key-managers/km.proto
- rina-tools/src/key-managers/kma.cc
- rina-tools/src/key-managers/kma.h
- rina-tools/src/key-managers/main.cc
- rinad/src/ipcp/ipc-process.cc
- rinad/src/ipcp/ipc-process.h
- rinad/src/ipcp/rib-daemon.cc
Code for Key Management demo: includes key management application (with Central Key Manager and Key Management Agents). Added minor updates and fixes to librina in order to allow applications other than IPCPs to properly use the authentication policies and carry out SDU protection in user space.
> Pristine 1.5 kmgmt

- rina-tools/configure.ac
- rina-tools/src/Makefile.am
- rina-tools/src/mac2ifname/Makefile.am
- rina-tools/src/mac2ifname/mac2ifname.c
Add simple tool useful for integration with buildroot
> rina-tools: add mac2ifname tool

- librina/src/core.cc
The last version of eventfd management was race-condition free, but affected by possible
spurious wake-ups, since the notifications (eventfd write) used to
happen before the event was pushed.
This new solution manages the race condition between write() and
read() by simply allowing the read() to block.
@edugrasa can you please verify that the race condition is not there and that there are no regressions?
> librina: core: use a better scheme for eventfd notifications

- rinad/src/ipcp/rib-daemon.cc
> rinad: eliminated duplicate callback in the RIB

- linux/net/rina/ipcps/shim-tcp-udp.c
This is waiting for the new shim-udp that will support multiple flows and do DNS queries.
> kernel: shim-tcp-udp: quick'n dirty way to update directory entries

- rina-tools/src/irati-ctl
irati-ctl: add --version option
> irati-ctl: add --version option

- rina-tools/src/rlite/rina-echo-async.c
> rina-tools: rina-echo-async: use non-blocking registration

- kernel/sdu.c
- rinad/src/ipcm/addons/mobility-manager.cc
- rinad/src/ipcm/addons/mobility-manager.h
- rinad/src/ipcp/shim-wifi/shim-wifi-ipc-process.cc
Updated mobility manager with "demo sequence" for 6 APs and 2 mobile net DIFs.
> Arcfire eucnc

- common/serdes-utils.c
Fixes issues in comparing strings at shim-tcp-udp
> common: fixed bug deserializing string

- kernel/dt-utils.c
- kernel/dt-utils.h
- kernel/dtcp-ps-default.c
- kernel/efcp.c
- kernel/efcp.h
* Fix bug in reliable flow destruction
* Fix estimation of RTT
* Fix timing of retx, implement exponential backoff
> Reliable flows fixes

- kernel/efcp.c
- rinad/src/ipcp/flow-allocator.cc
> Arcfire - fix rel flows bug

- kernel/dt-utils.c
- kernel/dt-utils.h
- kernel/dtcp-ps-default.c
- kernel/dtcp.c
- kernel/dtp-ps-default.c
And fixed order of ACK ctrl PDU processing workflow
> kernel: efcp: fixed bug in RTT estimator policy

- kernel/dt-utils.c
- kernel/dtp.c
- kernel/efcp.c
- rinad/src/ipcp/components.h
- rinad/src/ipcp/enrollment-task.cc
- rinad/src/ipcp/enrollment-task.h
- rinad/src/ipcp/flow-allocator.cc
- rinad/src/ipcp/plugins/default/enrollment-task-ps.cc
- rinad/src/ipcp/plugins/nsm-address-change/nsm-address-change-plugin.cc
* Fix race condition in EFCP connection initialisation
* Fix outdated address problem while enrolling with peer
> EFCP and enrollment task fixes

- rinad/src/ipcp/plugins/default/routing-ps.cc
Fix bug in routing policy (link state)
> Arcfire, link-state routing bug fix

- rina-tools/src/rlite/Makefile.am
- rina-tools/src/rlite/fdfwd.cpp
- rina-tools/src/rlite/fdfwd.hpp
- rina-tools/src/rlite/rina-echo-async.c
- rina-tools/src/rlite/rina-gw.cpp
- rina-tools/src/rlite/rinaperf.c
This includes updated rinaperf, rina-echo-async and introduces rina-gw to implement RINA/TCP gateway.
Documentaton for rina-gw is available here https://github.com/vmaffione/rlite#71-rina-gw
This pull request depends on #1141
> Upgrade RINA applications

- kernel/du.c
- kernel/ipcps/shim-eth-utils.c
- kernel/kfa.c
- kernel/pci.c
- kernel/rina-device.c
- kernel/utils.c
Add support for kernel versions 4.9 - 4.13 (4.0 to 4.9 already supported)
> Arcfire linux 4.13

- README.md
- kernel/configure
- librina/src/security-manager.cc
- rina-tools/src/key-managers/km-common.cc
- rinad/src/ipcm/addons/ma/ribf.cc
Support SSL libcrypto versions 1.0.x and 1.1.X. Fix #1096
> Arcfire ssl1.1

- .travis.yml
- ci/build-all
- ci/build-kernel
- configure
- kernel/rina-device.c
Various improvements:
- faster build process
- cleaner travis.yml
- support to check kernel build for all versions in 4.1-4.13
- other minor fixes
> Improve continuous integration

- rina-tools/src/rlite/rina-echo-async.c
- rina-tools/src/rlite/rina-gw.cpp
- rina-tools/src/rlite/rinaperf.c
Minor bug fixes and code improvements.
> rina-tools: align updated tools from rlite

- rina-tools/src/rlite/Makefile.am
- rina-tools/src/rlite/fdfwd.cpp
- rina-tools/src/rlite/fdfwd.hpp
- rina-tools/src/rlite/iporinad.cpp
- rina-tools/src/rlite/rina-gw.cpp
This patch also includes several changes that refactors iporinad
and the fdfwd lib.
> rina-tools: iporinad: detect and react to closed sessions

- librina/wrap/rina-api/include/rina/api.h
- librina/wrap/rina-api/src/rina-api.cc
- rina-tools/src/rinacat/rinacat.c
- rina-tools/src/rlite/rina-echo-async.c
- rina-tools/src/rlite/rina-gw.cpp
- rina-tools/src/rlite/rinaperf.c
Small API alignment.
It also introduces a version number in the flow spec to allow for extension.
> librina, rina-tools: align api, introducing qos version

- README.md
- rinad/src/ipcp/plugins/default/static-routing-ps.cc
* Improved capabilities of static routing policy
* Added information on the README on how to configure the different components of a DIF template, including details on the different policies available in IRATI
> Static routing policy improvements, more documentation

- librina/wrap/rina-api/include/rina/api.h
- rina-tools/src/rlite/rinaperf.c
- Import upgrades from upstream
- fix support for `max_loss` and `max_delay`
> Upgrade rinaperf

- rina-tools/src/rlite/CDAP.proto
- rina-tools/src/rlite/cdap.cpp
- rina-tools/src/rlite/cdap.hpp
- rina-tools/src/rlite/cpputils.hpp
- rina-tools/src/rlite/fdfwd.cpp
- rina-tools/src/rlite/iporinad.cpp
This includes various fixes and support for -E/-L arguments for
iporinad (max loss and max delay).
> rina-tools: upgrade iporinad, cdap and fdfwd

- librina/wrap/rina-api/include/rina/api.h
> librina: update rina/api.h with a comment on the naming conventions

- common/serdes-utils.c
- librina/src/ctrl.c
- rina-tools/configure.ac
- rina-tools/src/Makefile.am
- rina-tools/src/tgen-apps/Makefile.am
- rina-tools/src/tgen-apps/ra_base_client.h
- rina-tools/src/tgen-apps/ra_base_server.h
- rina-tools/src/tgen-apps/ra_commons.h
- rina-tools/src/tgen-apps/test_client_base.h
- rina-tools/src/tgen-apps/test_commons.h
- rina-tools/src/tgen-apps/tg-client.cpp
- rina-tools/src/tgen-apps/tg-server.cpp
And added a couple of fixes:
* remove too detailed debug messages in librina
* fixed rina name separator at RINA API level
> Eraser apps: integrated traffic generation apps from ERASER project

- kernel/dtcp.c
- kernel/dtp.c
- kernel/du.c
- kernel/ipcps/normal-ipcp.c
- kernel/pci.c
- kernel/pci.h
- rina-tools/src/tgen-apps/ra_commons.h
- rina-tools/src/tgen-apps/test_client_base.h
- rina-tools/src/tgen-apps/tg-server.cpp
* EFCP: detect padding added by N-1 layer 
* tgen-apps: fix uninitialized variable
> Fixed bugs in EFCP and tgen-apps

- rina-tools/src/rinacat/rinacat.c
> rina-tools: rinacat: add BSD license, reformat

- kernel/ctrldev.c
- kernel/ipcps/shim-eth-vlan-core.c
- kernel/pff-ps-default.c
- kernel/rds/robjects.c
Fix a kernel bug (use after free) and a number of memory leaks
> Memory related fixes

- kernel/ipcps/shim-eth-vlan-core.c
- kernel/rmt.c
* Fix bug that sometimes leaves the upper flow disabled forever
> Fix interaction with Linux transmission layer

- rina-tools/src/tgen-apps/README.md
- rina-tools/src/tgen-apps/tg-client.cpp
The application, depending on the used class of traffic, doesn't finish at the expected time when the link is saturated
> Fix end of experiment of tgen-app

- rina-tools/src/rlite/rinaperf.c
Needed for ARCFIRE experiment 2
> tools: rinaperf: add timestamp option for ping test

- README.md
- kernel/ipcps/shim-eth-vlan-core.c
- kernel/pff-ps-default.c
- plugins/qta_mux/qta-mux.c
- rinad/src/ipcm/dif-allocator.cc
- rinad/src/ipcp/components.h
- rinad/src/ipcp/enrollment-task.cc
- rinad/src/ipcp/enrollment-task.h
- rinad/src/ipcp/plugins/default/resource-allocator-ps.cc
- rinad/src/ipcp/plugins/default/routing-ps.cc
- rinad/src/ipcp/resource-allocator.cc
- rinad/src/ipcp/resource-allocator.h
* Add ability for the N DIF to request multiple N-1 flows with different QoS properties. Adapt the PDU  forwarding table generation policy to exploit this fact.
> Arcfire qos

- rina-tools/src/rlite/Makefile.am
- rina-tools/src/rlite/rinaperf.c
See https://github.com/rlite/rlite/issues/82
> rina-tools: upgrade rinaperf with ping statistics

- kernel/dtp-utils.c
- kernel/dtp.c
- kernel/efcp-str.h
- kernel/ipcps/normal-ipcp.c
- kernel/rds/rtimer.c
- kernel/rds/rtimer.h
Make it simpler and adapt to kernel 4.15+
> Arcfire: fix timers API

- README.md
- kernel/dtp-ps-default.c
- kernel/dtp.c
- rina-tools/src/manager/dif-template-manager.cc
- rina-tools/src/manager/dif-template-manager.h
- rina-tools/src/manager/net-manager.cc
- rina-tools/src/manager/net-manager.h
- rinad/src/ipcm/addons/ma/confm.cc
- rinad/src/ipcm/addons/ma/confm.h
- rinad/src/ipcm/addons/ma/flowm.cc
Add ability to create/destroy DIFs at once via the Manager.
Fix bug in EFCP.
> E2ens cdif: create/Destroy DIFs at once

- README.md
- configure
- kernel/dtp.c
- librina/src/Makefile.am
- librina/src/librinajsoncpp.pc.in
- rina-tools/configure.ac
- rina-tools/src/manager/Makefile.am
- rina-tools/src/manager/dif-template-manager.cc
- rina-tools/src/manager/dif-template-manager.h
- rina-tools/src/manager/net-manager.cc
- rina-tools/src/manager/net-manager.h
- rinad/src/common/Makefile.am
- rinad/src/common/librinad.pc.in
- rinad/src/ipcm/addons/ma/confm.cc
- rinad/src/ipcm/addons/ma/confm.h
- rinad/src/ipcm/addons/ma/flowm.cc
> Merge e2ens into master

- common/serdes-utils.c
- kernel/ctrldev.c
- kernel/delim-ps-default.c
- kernel/delim-ps-default.h
- kernel/delim-ps.h
- kernel/dtcp-conf-utils.c
- kernel/ipcps/shim-eth-vlan-core.c
- kernel/kfa.c
- kernel/kfa.h
- kernel/rmt.c
Fixed a number of memory leaks and bugs in the kernel
> kernel: fixed memleaks and bugs

- configure
- kernel/dtcp-ps-default.c
- kernel/dtcp-ps-default.h
- kernel/dtcp-ps.h
- kernel/dtcp.c
- kernel/dtcp.h
- kernel/dtp-ps-default.c
- kernel/dtp-utils.c
- kernel/dtp-utils.h
- kernel/dtp.c
- kernel/dtp.h
- kernel/efcp-str.h
- kernel/efcp.c
- kernel/pci.c
- kernel/pci.h
- kernel/rmt.c
- plugins/cong_avoidance/dtcp-ps-cas.c
- plugins/dummy/dtcp-ps-dummy.c
- plugins/rdsr-ps/cdrr/dtcp-ps-cdrr.c
- plugins/red/dtcp-ps-red.c
Implementation of the EFCP rendezvous mechanism, which manages closed windows. Includes fixes to EFCP locking and retransmission control.
> Rendezvous implementation

- .travis.yml
- kernel/dtp.c
- kernel/ipcps/shim-tcp-udp.c
- kernel/logs.h
> kernel: add support for kernel versions 4.16-4.19

- kernel/iodev.c
- kernel/kfa.c
- kernel/kfa.h
- kernel/kipcm.c
- kernel/kipcm.h
Add kernel support for S/G I/O
> E2ens: Kernel support for S/G I/O

- rinad/src/ipcm/addons/console.cc
- rinad/src/ipcm/app-handlers.cc
- rinad/src/ipcm/dif-allocator.cc
- rinad/src/ipcm/flow-alloc-handlers.cc
- rinad/src/ipcm/ip-vpn-manager.cc
- rinad/src/ipcm/ip-vpn-manager.h
- rinad/src/ipcm/ipcm.h
Decoupled IP VPN app names from IP address prefixes
> E2ens: address issue #1303

- kernel/ipcps/shim-eth-vlan-core.c
- rinad/src/ipcm/addons/console.cc
- rinad/src/ipcm/ipcm.cc
- rinad/src/ipcm/ipcm.h
- rinad/src/ipcm/ipcp.cc
- rinad/src/ipcm/ipcp.h
* Added ability to use a full Ethernet interface with an arbitrary DIF name on shim DIF over VLANs.
* Added ability at the IPCM (command line) to retrieve the interface name a certain IPCP is attached to (if any), given a DIF name.
> Edf improvements

- kernel/cidm.c
On multiprocessor systems doing a lots of local connection, it is frequent that an application triggers use-after-free errors in
the CIDM attribution code. List element that were freed were accessed in other CPUs.
> Protect use of the CEP-ID list
