- linux/net/rina/dtcp.c
- linux/net/rina/ipcps/shim-hv.c
- linux/net/rina/vmpi/vmpi-ops.h
- linux/net/rina/vmpi/vmpi-structs.h
Fix compilation problem that shows up when VMPI_TX_MUTEX is defined.
> vmpi: fix some include directives

- linux/net/rina/pci.c
When the PCI was created, source and destination cep-ids were set up one instead of the other, with pci_format doing the same
> Fixed bug in pci.c: refer to #491

- linux/net/rina/efcp.c
Fixed bad locking while creating a DTCP instance. It fixes #495, sleeping function called from invalid context.
> Pristine 1.2 #495

- librina/src/core.cc
- librina/src/netlink-manager.cc
- librina/src/netlink-messages.cc
- linux/net/rina/rnl.c
Fix applied as described in issue #497, and simplified log output for NL messages (more compact traces). Only notifications about closed NL sockets of Generic NL family are forwarded to user space now.
> Fix #497: filter non-related NL socket closed notifications and improve logging of NL messages

- librina/include/librina/Makefile.am
- librina/include/librina/likely.h
- librina/include/librina/logs.h
- librina/src/logs.cc
* Substituted rwlocks for a single mutex on logging stream setting
* Removing unnecessary (and expensive) double locking per trace call
> Simplyfing logging facility.Adding likely.h header

- rinad/src/ipcm/app-handlers.cc
- rinad/src/ipcm/ipcm.cc
Sorry, forgot to create a separate branch to address the issue. The fix is tested.
> Fix #517: cleanup of IPCP kernel state when detecting a crashed IPCP Daemon OS Process

- tests/conf/vm-to-vm/ipcmanager.conf-pm
- tests/conf/vm-to-vm/ipcmanager.conf-vm.1
- tests/conf/vm-to-vm/ipcmanager.conf-vm.2
Three configuration files for a normal-over-shim-hv test involving a physical machine and two virtual machines.
> tests/conf: add configuration files for vm-to-vm tests

- rinad/src/ipcm/app-handlers.cc
- rinad/src/ipcm/ipcm.cc
- rinad/src/ipcm/ipcp-handlers.cc
remove_transaction_state was called instead of remove_syscall_transaction_state
Also fixed condition in os_process_finalized event handler, in case an IPCP crashed.
> Pristine 1.2 #530: fix incorrect transaction handling in IPCP initialized response handler

- linux/net/rina/buffer.c
- linux/net/rina/buffer.h
- linux/net/rina/pdu-ser.c
- linux/net/rina/pdu-ser.h
- linux/net/rina/serdes.c
Added the necessary GFP flag handling so head grow/shrink functions can be called in the mode required by the context, i.e. non interruptible in interrupt context.
> Pristine-1.2 #531: Fixed bug in DU protection, sleeping functions called in invalid context

- tests/conf/vm-to-vm/ipcmanager.conf-pm
Add missing stanza for shim IPCP for HV creation on physical machine.
> tests/conf/vm-to-vm: add missing shim IPCP creation

- linux/net/rina/vmpi/vmpi-provider.c
Less obscure printk() to log registration/unregistration of a VMPI device.
> vmpi-provider: improve registration/unregistration logging

- librina/include/librina/configuration.h
- librina/src/application.cc
- librina/src/netlink-parsers.cc
- librina/src/netlink-parsers.h
- rinad/etc/ipcmanager.conf.in
- rinad/src/common/rina-configuration.h
- rinad/src/ipcm/configuration.cc
- rinad/src/ipcm/ipcm.cc
- rinad/src/ipcp/ipc-process.cc
- rinad/src/ipcp/ipc-process.h
- tests/conf/ipcmanager.conf-normaloverdummy
- tests/conf/ipcmanager.conf-normalovereth1
- tests/conf/ipcmanager.conf-normalovereth2
- tests/conf/ipcmanager.conf-normalovereth2cubes
- tests/conf/ipcmanager.conf-normalovernormalovereth1
- tests/conf/ipcmanager.conf-normalovernormalovereth2
- tests/conf/ipcmanager.conf-normalovershimhv1
- tests/conf/ipcmanager.conf-normalovershimhv2
- tests/conf/ipcmanager.conf-normalovertcpudp1
- tests/conf/ipcmanager.conf-normalovertcpudp2
- tests/conf/vm-to-vm/ipcmanager.conf-pm
- tests/conf/vm-to-vm/ipcmanager.conf-vm.1
- tests/conf/vm-to-vm/ipcmanager.conf-vm.2
Allow IPCM configuration file to specify the name of policy sets to be selected at assign-to-dif time, for userspace IPCP components.
Pull request also includes update to test configuration files
> Allow IPCM configuration file to specify policy-sets for userspace components

- rinad/src/common/encoders/FlowMessage.proto
Make .proto definitions more uniform by removing unnecessary namespace prefix.
> rinad: encoders: remove unnecessary prefixes

- rinad/src/ipcm/policies-handlers.cc
Return values of policy-set handlers operation were not propagated up correctly (error introduced by IPCM refactor).
> IPCM: fix policy-set handlers

- librina/include/librina/irm.h
- librina/src/irm.cc
- rinad/src/ipcm/addons/console.cc
- rinad/src/ipcm/app-handlers.cc
- rinad/src/ipcm/ipcm.cc
- rinad/src/ipcm/ipcm.h
- rinad/src/ipcm/ipcp-handlers.cc
- rinad/src/ipcp/resource-allocator.cc
Fixed a couple of bugs:
* Fixed handling of object value in IRM RIB objects, before could lead to seg faults
* Fixed IPCM deadlocks when processing unregister-from-dif and register-at-dif operations
* Fixed bug in IPCM register-at-dif respone handler
> Pristine 1.2

- linux/net/rina/rmt-ps-default.c
Just a simple fix in argument pointer type.
> Fix RMT policy set compilation warning

- rinad/src/ipcm/ipcm.cc
Fixing (self-introduced) bug during IPCM shutdown process. Condition needs to
be signaled even if librina is not producing ANY event.
> Fix ipcm deadlock when no events are received

- rinad/src/ipcp/main.cc
When debugging the IPCM in gdb, if SIGINT is not ignored, a Ctrl+C in the
debugger signals the child process and, since it is not captured, it dies.
This patch sets SIGINT to be ignored by IPCPs.
This patch requires commit 698eb30198226ac4b3e3d264af1183a5206a7fd1 PR to be
integrated first.
> Ignore SIGINT in IPC processes

- linux/net/rina/ipcps/shim-eth-vlan.c
A VLAN id 0 is interpreted as "no VLAN, untagged frames".
> Allowed shim-eth-vlan to have untagged frames.

- librina/src/concurrency.cc
This was resulting in a compilation error induced by -Werror.
> librina: concurrency: use reinterpret_cast<> to avoid compiler errors

- linux/net/rina/efcp.c
- linux/net/rina/ipcp-instances.c
- linux/net/rina/ipcp-instances.h
- linux/net/rina/ipcps/normal-ipcp.c
- linux/net/rina/ipcps/shim-eth-vlan.c
- linux/net/rina/ipcps/shim-hv.c
- linux/net/rina/ipcps/shim-tcp-udp.c
- linux/net/rina/kfa.c
- linux/net/rina/kipcm.c
Related to #595 some other bugs where discovered and fixed by means of a new op in the normal_ipcp api. It has to be merged in pristine-1.2 and ported to pristine-1.3.
Tested and working, @bernatgaston  to test again and ack it.
> Fixed bug on not releasing port_ids after failed flow allocation resulting in port_ids exhaustion

- rinad/src/ipcp/plugins/default/routing-ps.cc
This fixes wrong logic in Edge::operator==.
> rinad: ipcp: fix Edge equality operator logic

- linux/net/rina/rmt-ps-common.c
- linux/net/rina/rmt.c
> Adding missing clean up functions in the n1_port creation when binding an upper normal IPCP

- linux/net/rina/pci.h
The ECN flag was missing, while there were introduced flags specified for the SDU delimiting that had to be removed.
> Added ECN flag to the PDU flags and removed wrong flags

- librina/test/test-01.cc
librina tests (make check) do not compile with clang due to the use of '+'
operator to concatenate strings.
Subsitute '+' for '<<' to concatenate strings.
> librina: fix make check (clang)

- librina/test/test-01.cc
- rinad/src/ipcp/plugins/default/test-routing.cc
- rinad/src/ipcp/test-encoders.cc
A couple of fixes on rinad's `make check`
**WARNING**: this commit contains _intentionally_ #621, so please ACK and merge #621 first
> Fix rinad IPCP tests in pristine-1.2

- linux/net/rina/rmt.c
This contains a fix for #628 and does not include the workaround of pull request #629. It also fixes another bug discovered when the n1_port is destroyed within the do_while loop in the send_worker.
It needs to be better tested, in the same environment where the error was discovered.
> Pristine 1.3: Fix for issue #628

- rinad/src/ipcm/dif-template-manager.cc
Which did not properly initialize the security manager policy set of templates that extended default.dif
> fixed bug in template manager

- linux/net/rina/dtp.c
The to_post queue was reintroduced in dtp_receive and a-timer so that these operations just take the lock of the seqq to update window edges and select the pdus from the seq_queue to be pushed/forwarded. When done lock is released and the actual push/forwarding is done with no lock taken.
> Added a queu to store the pdus to be processed in dtp_receive and a-timer

- linux/net/rina/ipcp-instances.h
- linux/net/rina/ipcp-utils.c
- linux/net/rina/rmt.c
Fixed errors when setting the encryption key:
* No need to store the key in the config (it is useless and uses memory for nothing). Moreover, there was a bug since the key is destroyed by the KIPCM before returning from the 'enable_encryption' function, and the RMT was destroying the entry again when destroying the N-1 port.
* No need to copy the key before setting it at the blockcipher, since the blockcipher copies it.
> Pristine 1.3 Fix errors when setting encryption key

- MAINTAINERS
This patch fixes the inconsistencies detected in the MAINTAINERS
file in pristine-1.3 branch. From this point on, PR shall update
themselves the MAINTAINERS file.
fixes #645
> Adapting MAINTAINERS file to 1.3

- linux/net/rina/rmt.c
This commit fixes two compilation warnings in rmt.c, which were
introduced during the last couple of commits related to the
authentication policies.
Fixes #649
Maintainer: @miqueltarzan
> linux: Fix two warnings in rmt.c

- rinad/src/ipcp/plugins/default/test-routing.cc
The problem was due to a missing implementation of a pure
virtual method for the class FakeRIBDaemon.
Fixes #647.
> rinad: make check: fix compilation error

- check_maintainers.py
This patch adds the functionality to check_maintainers.py to list
the maintainers of the files that a commit or a series of commits
affect.
It supports:
* Checking a (single) patch file
* Checking last N commits in the current branch
* Checking against the current HEAD with a ref (e.g. a git tag)
Other improvements:
* Adding help option '-h'
* Minor cosmetics to the code
> check_maintainers: list maintainers of a patchset

- check_maintainers.py
Fixed following bugs in check_maintainers.py:
* -l was incorrectly ignoring file names due to non-implicit
conversion of bytestring to str
* include MAINTAINERS file.
> check_maintainers: fix python3 and misc bugs

- linux/net/rina/ipcps/shim-hv.c
Add missing return type declaration.
> kernel: shim-hv: fix compilation warning

- linux/net/rina/dtcp.c
- linux/net/rina/pff.c
- linux/net/rina/rmt.c
With this patch rmt_select_policy_set() and rmt_set_policy_set_param()
calls pff_select_policy_set() and pff_set_policy_set_param(),
when needed.
@sandervrijders @miqueltarzan @lbergesio : waiting for your ACKs.
> kernel: pff: add component delivery workflow SDK support

- linux/net/rina/rnl-utils.c
This PR fixes #574. EFCP QoS cubes are not needed in the kernel at the moment. The NL message contains them because of user space dependencies. Until a needed of parsing and using this information appears they can be simply obviated and so remove the LOG_MISSING statement.
I am the maintainer of this file, so it is an ack from me. Since it is a very trivial change I guess it can be merged by any admin directly.
root@irati-vm-leo-1:/home/irati# python check_maintainers.py -n -l 1
F: linux/net/rina/rnl-utils.c
Leonardo Bergesio <leonardo.bergesio (at) i2cat.net>
> QOS_CUBES obviated in RNL. fix #574

- linux/net/rina/ipcp-instances.h
- linux/net/rina/ipcps/normal-ipcp.c
- linux/net/rina/ipcps/shim-eth-vlan.c
- linux/net/rina/ipcps/shim-hv.c
- linux/net/rina/ipcps/shim-tcp-udp.c
With this patch, a new operation called nm1_flow_state_change has been added to the IPCP kernel ops. The purpose of this operation is to inform an IPCP that an N-1 flow has gone "up" or "down". A stub for this operation has been implemented for the normal IPCP kernel implementation - it just logs the event for now.
The shim-eth-vlan implementation has been upgraded to detect up/down events of the associated network interface and consequently notify the N+1 IPCP that is using the flows provided by the shim.
Waiting to be acked by:
@sandervrijders 
@miqueltarzan
> Shim eth vlan can notify user IPCPs about flows going up and down

- linux/net/rina/ipcps/Kconfig
- linux/net/rina/ipcps/shim-eth-vlan.c
Added a check for max SDU size in shim-eth-vlan write (max size configurable via kconfig)
Maintainers:
@sandervrijders
> Pristine 1.3 shim eth size

- linux/net/rina/ipcps/shim-eth-vlan.c
This PR removes an unused variable in eth_vlan_sdu_write
that only adds to the confusion.
Tested with 2 nodes and rina-echo-time.
Maintainer: Myself, so can someone else ACK and merge this into pristine-1.3, integration-1.2, pristine-1.2?
> kernel: shim-eth-vlan: Remove rinarp_mac_addr

- rinad/src/ipcm/ipcm.cc
- rinad/src/ipcm/ipcm.h
This patch allows ipcm to modprobe/rmmod plugin modules.
Maintainers: @msune
> rinad: ipcm: implement plugin_load_kernel()

- linux/net/rina/ipcps/normal-ipcp.c
- linux/net/rina/rnl-utils.c
* Fixed null pointer access when destroying a normal IPCP over a normal IPCP with a flow allocated
* Fix handling of not-present SDU protection configuration in kernel space (Fixes issue #675)
Maintainers: @lbergesio @miqueltarzan
> Fixed two bugs in kernel space (non-present SDU protection config handling and destruction of normal over normal)

- linux/net/rina/ipcps/normal-ipcp.c
- linux/net/rina/ipcps/shim-eth-vlan.c
- linux/net/rina/pff-ps-default.c
- linux/net/rina/pff-ps.h
- linux/net/rina/pff.c
- linux/net/rina/pff.h
- linux/net/rina/rmt.c
- linux/net/rina/rmt.h
The pff_port_state_change() operation has been added to the policy set in order to receive notifications about flow going up or down.
> kernel: pff-ps: add pff_port_state_change() op

- MAINTAINERS
- plugins/lfa/.gitignore
- plugins/lfa/Makefile
- plugins/lfa/ps.c
This pull request contains the implementation of the LFA policy, needed for PRISTINE T4.3 resiliency work. Added myself as maintainer. It has been tested and it works like the default policy set in the normal case (apart from the fact that it doesn't support multicast, but this is not happening in user-space at the moment either). 
It also responds to flow up and down events. The policy also takes a module parameter to react differently to flow up events, for testing purposes. Since the alternate entries are not propagated to kernel space yet, not all cases have been tested yet. In the case of no available LFAs, the policy works. Propagation of LFA entries to kernel space is foreseen in a next pull request. 
Maintainers: @msune and myself. @vmaffione Can you have a look since I cannot ACK …
> Implementation of the Loop-Free Alternates policy 

- plugins/lfa/ps.c
This patch fixes a bug in lfa_add. The for loop always ended one entry
too soon, making some alternates disappear.
Maintainer: Myself.
> plugins: lfa: Fixes bad index in for loop

- librina/include/librina/ipc-process.h
- rinad/src/ipcp/plugins/default/resource-allocator-ps.cc
- rinad/src/ipcp/plugins/default/routing-ps.cc
This patch series contains the modification necessary to correctly compute LFA nodes for the routing table and correctly translate NextHop information into PortId information, so that the resulting PDU Forwarding table (that includes lists of alternate port-ids) is pushed to kernelspace to the PFF component.
> Completing LFA implementation in userspace

- rinad/src/ipcm/main.cc
ipcm manager now exits cleanly upon killing through the kill command and accidental ssh disconnects.
easiest way to test this PR, start your ipcm and then try the following commands
```
sudo kill <pid>
sudo kill -SIGINT <pid>
sudo kill -SIGHUP <pid>
sudo kill -SIGTERM <pid>
sudo kill -SIGQUIT <pid>
```
and restart the ipcm after each.
Maintainer: @msune
> rinad: ipcm: added graceful exit upon SIGQUIT, SIGTERM, SIGHUP

- MAINTAINERS
- plugins/cong_avoidance/Makefile
- plugins/cong_avoidance/cas-plugin.manifest
- plugins/lfa/Makefile
- tests/conf/ipcmanager.conf-appovereth
- tests/conf/ipcmanager.conf-appovershimhv
- tests/conf/ipcmanager.conf-mad
- tests/conf/ipcmanager.conf-normalovereth1
- tests/conf/ipcmanager.conf-normalovereth2
- tests/conf/ipcmanager.conf-normalovernormalovereth1
- tests/conf/ipcmanager.conf-normalovernormalovereth2
- tests/conf/ipcmanager.conf-normalovershimhv1
- tests/conf/ipcmanager.conf-normalovershimhv2
- tests/conf/ipcmanager.conf-normalovertcpudp1
- tests/conf/ipcmanager.conf-normalovertcpudp2
- tests/conf/vm-to-vm/ipcmanager.conf-pm
- tests/conf/vm-to-vm/ipcmanager.conf-vm.1
- tests/conf/vm-to-vm/ipcmanager.conf-vm.2
- tests/conf/vpn/ipcmanager.conf-pm.i2cat
- tests/conf/vpn/ipcmanager.conf-pm.nxw
- tests/conf/vpn/ipcmanager.conf-vm.i2cat
- tests/conf/vpn/ipcmanager.conf-vm.nxw
With this patch, non-default plugin manifests are installed in the system in the same place compiled modules are installed in the system - under /lib/modules/`uname -r`.
In this way IPCM configuration file can specify a single entry in pluginsPaths to indicate where the manifest files for kernel plugins can be found.
Maintainers:
@lbergesio @msune
> Fix deployment of manifest files for kernel plugins

- rinad/src/ipcp/plugins/default/test-routing.cc
This problem was introduced by the change in RoutingTableEntry
data structure, due to the introduction of LFA alternates.
Fixes #694
> rinad: ipcp: fix test-routing compilation error

- plugins/cong_avoidance/dtcp-ps-cas.c
- plugins/cong_avoidance/rmt-ps-cas.c
This PR fixes and extends #703 which was originally nacked by me.
It implements the Jain binary congestion avoidance scheme as a pair of PSs for DTCP and RMT.
It has been tested and used in the first experiment scenario of D6.2.
Mainteiners: @miqueltarzan and myself.
> Pristine 1.3 jain dtcp ps

- linux/net/rina/dtcp.c
Nothing prevents a PS to not define the rtt_estimator op and set it
to NULL. If this happens, the DTCP code executes the op without checking
if the pointer is not NULL and the system crashed.
The proper solution would be to check for mandatory ops in the PS, but in
the meanwhile this solves the problem.
I am the maintainer, but changes are trivial so anyone with rights can check and merge.
> pristine-1.3: kernel: dtcp: check ps->rtt_estimator is not NULL

- linux/net/rina/dtp.c
- rinad/src/ipcm/catalog.cc
The processing of DTP and DTCP policy set configurations was
missing.
Maintainers:
@lbergesio 
@msune
@kewinrausch, this will solve your problem
> Fix catalog for automatic loading of policy-sets

- linux/net/rina/ipcps/shim-eth-vlan.c
shim-eth-vlan.c : moved null_ptr check within spinlock, (fixes #721)
added null_ptr checks and ASSERTs to other functions,
removed eth_vlan prefix from internal functions eth_vlan_update_qdisc and eth_vlan_restore_qdisc
MAINTAINER: @sandervrijders
> Bugfix in shim-eth-vlan, locking issue, fixes #721

- linux/net/rina/ipcps/shim-eth-vlan.c
Lock was not released immediately, causing update_qdisc() routine -
which can sleep - to be called under that lock, that does not
allow for sleeping.
Fixes #729 
Maintainers: @sandervrijders
> shim-eth-vlan: fix bad locking when accessing device list

- MAINTAINERS
- misc/code-stats
This patch adds a code statistic, showing how many lines have
been edited since the end of IRATI.
maintainers:
@vmaffione
@msune
> misc/code-stats: add total diff w.r.t. IRATI v1.0.0

- linux/net/rina/ipcps/shim-eth-vlan.c
Fixes #734; fixed bug in update and restore qdisc, adding also support for devices with multiple tx queues
> kernel: shim-eth-vlan: fixed bug in update and restore qdisc, adding also support for devices with multiple tx queues

- librina/include/librina/application.h
- rinad/etc/default.dif
- rinad/src/ipcm/addons/console.cc
- rinad/src/ipcm/addons/console.h
- rinad/src/ipcm/catalog.cc
- rinad/src/ipcm/catalog.h
- rinad/src/ipcm/configuration.cc
- rinad/src/ipcm/ipcm.cc
- rinad/src/ipcm/ipcm.h
- rinad/src/ipcm/ipcp-handlers.h
- rinad/src/ipcm/policies-handlers.cc
This PR introduces the following changes:
- Add support to keep track of which policy-set is currently being selected for a given component of an IPCP.
- Improved the show-catalog IPCM console command to show the new information
- Improved the show-catalog IPCM console commend to show only information related to a single component (e.g. show-catalog pff).
- Reworking of the catalog implementation, to use pointers instead of iterators.
- Add update-catalog command, to rescan the pluginsPaths directory and update the catalog.
- Some minor fixes to configuration files and implementation of a simple toString() method in librina
You can test by using select-policy-set command in the IPCM console and examining how the show-catalog output changes accordingly.
MAINTAINERS:
@edugrasa 
@msune
> Track selected policy sets

- librina/include/librina/application.h
- librina/src/application.cc
- librina/wrap/librina.i
- rinad/etc/default.dif
- rinad/src/ipcm/addons/console.cc
- rinad/src/ipcm/addons/console.h
- rinad/src/ipcm/catalog.cc
- rinad/src/ipcm/catalog.h
- rinad/src/ipcm/configuration.cc
- rinad/src/ipcm/ipcm.cc
- rinad/src/ipcm/ipcm.h
- rinad/src/ipcm/ipcp-handlers.h
- rinad/src/ipcm/policies-handlers.cc
- rinad/src/ipcp/plugins/default/plugin.cc
- rinad/src/ipcp/plugins/sm-passwd/security-manager-passwd.cc
With this patch, the plugin init() function is replaced by the get_factories() function. In this way, the IPCP acts as a master and asks the plugin for its policy sets. This simplifies the implementation and remove thread-safety-related problems.
This PR depends on #739 (includes it).
MAINTAINERS:
@edugrasa
> Userspace plugins: replace init() function with get_factories()

- MAINTAINERS
- librina/Makefile.am
- librina/configure.ac
- librina/include/librina/Makefile.am
- librina/m4/ax_selector_disable.m4
- librina/src/Makefile.am
- librina/wrap/c/Makefile.am
- librina/wrap/c/include/Makefile.am
- librina/wrap/c/include/librina-c/Makefile.am
- librina/wrap/c/include/librina-c/librina-c.h
- librina/wrap/c/src/Makefile.am
- librina/wrap/c/src/flow.cc
- librina/wrap/c/src/init.cc
- librina/wrap/c/src/ipcevent.cc
- librina/wrap/c/src/ipceventproducer.cc
- librina/wrap/c/src/ipcmanager.cc
- librina/wrap/c/src/librina-c.pc.in
Adds a library for calling librina from C programs. It is required for the upcoming ioq3 port. The c bindings are installed by default, but can be disabled by passing the --disable-c-bindings flag to ./configure (librina).
Maintainers: @msune for MAINTAINERS file, @dstaesse for the rest. 
Makefiles seem missing from MAINTAINERS, probably should be checked by @edugrasa and @vmaffione.
> librina: Added bindings for C

- rinad/src/common/Makefile.am
- rinad/src/common/debug.cc
- rinad/src/common/encoder.cc
debug.cc contained config.h which was unneeded.
header inclusion in common was doing and unneeded loop (going down
in the folder structure to go up later)
Ack need from @edugrasa
> rebase&clean: header cleanage

- librina/configure.ac
- rinad/configure.ac
Looks like inverted logic applied on the maven check.
Steps to reproduce:
rm -rf build
./install-user-from-scratch <folder>
@vmaffione (as this concerns autoconfigure)
> Fix issue #773: Misleading warning of missing maven build tool

- librina/wrap/librina.i
1. Fixes a NPE, passes events to the Java application
2. Fixes wrapping code generating calls to non-existent Java exceptions. (segfaults) 
@bernatgaston
> Fix for #683, and related Java VM crashes

- linux/net/rina/ipcps/shim-eth-vlan-core.c
- linux/net/rina/rmt-ps-default.c
- linux/net/rina/rmt-ps-default.h
- linux/net/rina/rmt-ps.h
- linux/net/rina/rmt.c
- linux/net/rina/rmt.h
- plugins/cong_avoidance/dtcp-ps-cas.c
- plugins/cong_avoidance/rmt-ps-cas.c
- plugins/dummy/dtcp-ps-dummy.c
- plugins/dummy/dtp-ps-dummy.c
- plugins/dummy/rmt-ps-dummy.c
- plugins/red/dtcp-ps-red.c
- plugins/red/rmt-ps-red.c
Concurrent writes are not longer allowed by means of a new boolean state variable in the n1_port. This should solve the problem with the pending_sdu being lost.
RMT PS simplified due to changes in RMT mechanism.
Some FIXMEs added, but this PR is blocking.
> Pristine 1.4 Changes in RMT  to solve write problem

- linux/net/rina/rmt-ps-default.c
Now layer mgmgt PDUs are put in a dedicated queue (with no max size) and dequeued first always.
It doesn't completely solve the problem for multiple layers, but we can't do better until we have separate layer management and data transfer flows.
Maintainers: @lbergesio
> Introduced prioritization of layer mgmt. PDUs in RMT default policy

- tests/conf/default.dif
Before this patch, using default.dif leads to failures due to
invalid (incomplete) data transfer constants.
MAINTAINERS: @edugrasa
> Update default.dif to last DIF validation algorithms

- plugins/red/rmt-ps-red.c
Also do correct cleanup on error conditions.
The missing check was leading to kernel crashes when policy-set selection was performed dynamically (select-policy-set).
MAINTAINERS:
@lbergesio
> plugins: red: check return value of rmt_config_get()

- check_maintainers.py
check-maintainers script now accepts -g option to present the modified files
grouped by the maintainers. This eases the copy-paste process to do a PR in
github.
Example output:
root@e2-leo-vm1:/home/irati/stack# python check_maintainers.py -n -l 3 -g
M: Bernat Gaston <bernat.gaston (at) i2cat.net>
librina/include/librina/cdap_v2.h
librina/src/cdap_v2.cc
M: Vincenzo Maffione <v.maffione (at) nextworks.it>
rinad/src/ipcp/resource-allocator.cc
M: Marc Sune <marc.sune (at) bisdn.de>
check_maintainers.py
librina/include/librina/rib_v2.h
rinad/src/ipcm/ipcm.h
M: Leonardo Bergesio <leonardo.bergesio (at) i2cat.net>
librina/src/netlink-parsers.cc
M: Eduard Grasa <eduard.grasa (at) i2cat.net>
librina/include/librina/configuration.h
Maintainer: @msune
> check-maintainers:option to group by maintainers

- linux/net/rina/rmt-ps-default.c
- plugins/cherish-urgency/cherish-urgency.c
- plugins/rdsr-ps/ecn/rmt-ps-ecn.c
- plugins/red/rmt-ps-red.c
When using the select-policy-set command from IPCM console, rmt_config_get() returns NULL.
Some plugins were crashing because they didn't check the return value.
MAINTAINERS:
M: Leonardo Bergesio <leonardo.bergesio (at) i2cat.net>
plugins/red/rmt-ps-red.c
plugins/red/rmt-ps-red.c
M: Miquel Tarzan <miquel.tarzan (at) i2cat.net>
linux/net/rina/rmt-ps-default.c
plugins/cherish-urgency/cherish-urgency.c
@lbergesio @miqueltarzan
> plugins: rmt: manage cases when rmt_config_get() returns NULL

- MAINTAINERS
- plugins/Makefile
- plugins/cherish-urgency/Makefile
- plugins/cong_avoidance/Makefile
- plugins/dummy/Makefile
- plugins/example-sm-plugin/Makefile
- plugins/lfa/Makefile
- plugins/multipath/Makefile
- plugins/rdsr-ps/Makefile
- plugins/rdsr-ps/cdrr/Makefile
- plugins/rdsr-ps/ecn/Makefile
- plugins/rdsr-ps/fare/Makefile
- plugins/red/Makefile
Add a build system for the out-of-tree plugins.
In the plugin/ directory, it is possible to start the compilation and installation of all the plugins at once
````
$ make INSTALLDIR=/path/to/irati/install/dir/
$ sudo make INSTALLDIR=/path/to/irati/install/dir/ install
````
If the KDIR directory is not specified, the linux/ directory in the repository will be used as default. This could be used to address some concerns related to #823 .
Need ACK from:
@edugrasa @kewinrausch @lbergesio @miqueltarzan @sandervrijders
> Plugin build system

- librina/src/ipc-process.cc
- linux/net/rina/kipcm.c
- linux/net/rina/syscalls.c
- rinad/src/ipcp/rib-daemon.cc
Fixes #825
Added error codes on the kernel side that are caught in the userspace.
When a critical error occurs on the read of the mng sdu in the kernel
it means that the kernel side of the normal IPCP is being closed.
In this case the userspace stops the thread that is polling
the kernel
Comes from https://github.com/IRATI/stack/pull/826 which closed due to an error when uploading the changes. Only need the ack from @edugrasa
> Gracefully closing of the read mng thread

- librina/include/librina/application.h
- librina/include/librina/timer.h
- librina/src/application.cc
- librina/src/core.cc
- librina/src/ipc-manager.cc
- librina/src/timer.cc
- rinad/src/common/encoders/IntType.proto
- rinad/src/common/encoders/Makefile.inc
- rinad/src/ipcp/ipc-process.cc
- rinad/src/ipcp/ipc-process.h
- rinad/src/ipcp/main.cc
- rinad/src/ipcp/resource-allocator.cc
Fixed 2 errors:
1. A protobuffer closure problem that was introducing memory leaks when closing the ipcm
2. The capture of the SIGINT signal by the IPCP and the closure of the IPCP without segfaults.
Need ack from @vmaffione and @edugrasa
> Pristine 1.4 fix valgrind closure

- rinad/src/common/encoder.cc
> rinad: common: encoders: remove spurious include directive

- linux/net/rina/ipcp-factories.c
This PR fixes #838.
needed ack from @vmaffione
> Pristine 1.4 fixed wrong dereference in ASSERT

- rinad/src/ipcm/ipcm.cc
Valgrind detected a memory leak problem when unregistering app
in rinad. This happened because of exceptions being thrown without
freeing the appropiate memory
ack @edugrasa
> Memory leack while unregistering app

- rinad/src/ipcm/addons/ma/flowm.cc
- rinad/src/ipcm/ipcm.cc
Fixes #851 . The order of destroying IPCP and addons has been changed.
Now, IPCPs are destroyed before addons to avoid the MA being stuck on
the threads reading these IPCPs. Moreover, the loop of the MA reading
on the flows have been changed to allow exit from this loop.
ack @edugrasa
> MA stuck when closing flows

- rinad/src/ipcp/plugins/default/Makefile.am
Fixes #852. A previous commit 2718f6ece0bf8b6462439a8695e5d3fc4f1ad52e
broke the rinad tests
ack @vmaffione
> Fix rinad tests

- plugins/cherish-urgency/Makefile
- plugins/cong_avoidance/Makefile
- plugins/lfa/Makefile
- plugins/multipath/Makefile
- plugins/rdsr-ps/cdrr/Makefile
- plugins/rdsr-ps/ecn/Makefile
- plugins/red/Makefile
This makes sure modprobe works as expected after make install.
This fixes #860 
ACK:
@kewinrausch
> plugins: add depmod -a instruction in install targets

- rinad/src/ipcm/ipcm.cc
Wrong handling of transactions code in IPCM caused it to terminate when an application was unregistered.
@vmaffione could you test it? It's quick, just register and unregister an application several times and make sure IPCM is still alive.
> rinad: ipcm: fixed bug when unregistering apps

- rinad/src/ipcp/plugins/default/routing-ps.cc
- rinad/src/ipcp/plugins/default/routing-ps.h
When a neighbor is lost, the routing was erasing all the FSOs
that had a realtion which such neighbor. It has only to erase
the direct link between curren IPCP and the neighbor and not
any remote link with the address of the neighbor.
Fixes #864
> neighbor lost bug fix

- librina/include/librina/security-manager.h
- librina/src/security-manager.cc
- rina-tools/src/util-scripts/rmt-port-monitor.sh
- rinad/src/ipcp/plugins/default/enrollment-task-ps.cc
Fixed an issue identified by Sarah from Thales: the policy was using a single RSA key pair for both authenticating parties, which doesn't make a lot of sense and is not how SSH operates.  Now is updated so that each IPCP has its own RSA key pair. Therefore, each IPCP needs to know the public keys of the IPCPs it wants to establish an application connection to.
The code is slightly changed, as well as the configuration of this policy. Now the "keystore_path" configuration parameter expects a path to a folder (terminating without "/"). The contents of the folder should be the following files:
* **key** : The RSA private key of the IPCP in PEM format (generated for example with _openssl genrsa -out key 2048_)
* **public_key**: The RSA public key of the IPCP in PEM format (extracted from the …
> Pristine 1.5 authssh

- linux/net/rina/rds/robjects.h
The issue was reported to me by @sandervrijders. The patch has been tested and seems to remove the warning he was getting when compiling with clang (gcc was not doing that afaik).
> kernel: sysfs: fix CLANG warning on sysfs_create_file return value

- rinad/src/ipcm/ipcm.cc
The output
````
modprobe: FATAL: could not...
````
used to show up in the logs (e.g. when loading the default userspace plugin), but it is not an error. It is just an indication that the plugin that the IPCM wants to load is not a kernel module.
This patch hides the output using stderr/stdout redirection.
> IPCM: Hide modprobe output when failing to load a module

- linux/net/rina/ipcps/shim-eth-vlan-core.c
Original code was:
rfifo_destroy(flow->sdu_queue, (void (*)(void *)) pdu_destroy);
when it should be passing sdu_destroy.
It probably never broke because the sdu_queue was already empty since it is
used only during flow allocation.
> kernel:shim-eth-vlan: fixed callback when sdu_queue is destroyed

- rinad/configure.ac
Current configure script ignores the --disable-java-bindings
switch.
This patch aims at making it possible to configure and build rinad without any Java installation on the local machine.
> rinad: configure: process --disable-java-bindings

- linux/net/rina/ipcps/shim-tcp-udp.c
Just to avoid the compiler warning about a couple of
"warning: control reaches end of non-void function [-Wreturn-type]"
> kernel:shim-tcp-udp: fix compilation warning

- install-user-from-scratch
- librina/configure.ac
- rina-tools/configure.ac
- rinad/configure.ac
For librina, rinad and rina-tools
fixes #890
Be aware that this change affects the default compilation of the stack
as --enable-debug is activated by default, and from now on this will
imply -O0, so decreases in performance should be expected.
To get the former performance you should disable --enable-debug
in the configuration scripts
> Fixes the parsing of debugging flags in CXXFLAGS

- linux/net/rina/rmt.c
n1_port_write_sdu only considered a -EAGAIN coming from the sdu_write ops as
only possible error. If -1 was returned by the op, n1_port_write_sdu was
obviating this and returning the bytes of the sdu supposedly written.
> kernel:rmt:fixed wrong return in n1_port_write_sdu

- rinad/src/ipcp/enrollment-task.cc
- rinad/src/ipcp/enrollment-task.h
Fixed wrong parameter type in read object api that prevented the method in the derived class from being called.
> rinad: enrollment: fixed wrong inheritance by WatchdogRIBObject

- librina/include/librina/cdap_v2.h
- librina/include/librina/rib_v2.h
- librina/src/cdap_v2.cc
- librina/src/rib_v2.cc
- librina/test/test-rib_v2.cc
- rinad/src/common/encoder.cc
- rinad/src/ipcm/addons/console.cc
- rinad/src/ipcm/addons/ma/flowm.cc
- rinad/src/ipcm/addons/ma/ribs/ipcp_obj.cc
- rinad/src/ipcm/addons/ma/ribs/ipcp_obj.h
- rinad/src/ipcm/ipcm.cc
- rinad/src/ipcm/ipcm.h
- rinad/src/ipcp/rib-daemon.cc
Flags where not being encoded as expected. Delegation objects are now
being sent to the manager controling the invoke_id used as response and
also the port of the conexion (which was not being stored, and hence,
not allowing multiple managers). It also deals with the race condition
generated by the delegation on the last object sent to the manager
(with no flags) that finishes the flow of cdap objects. To control
this problem, the MA will not sent its last RIB object until all
the delegated objects have finished their work and hence, all the
delegated objects have been send by the MA to the manager. Then,
the MA will send the last response object of the cdap flow for a
given invoke_id
Fixes #932
Fixes #934
Ack @edugrasa @vmaffione
> Delegation of objects various bugs fixed

- librina/wrap/c/include/librina-c/librina-c.h
- librina/wrap/c/src/librina-c.cc
The C wrapper now has init and fini functions, to initialize librina
and clean up any flows that weren't deallocated. It also fixes some
other bugs, such as catching all exceptions, as suggested by Marc.
> librina: Updated C wrapper

- plugins/lfa/ps.c
When the qos-id in a PFF entry is 0, it means it can serve requests
with any QoS ids. This patch implements this behaviour for the LFA
plugin, similarly to what is done for the PFF default plugin.
Without this patch, the LFA next-hop policy does not work correctly.
> plugins: lfa: align pft_find method to the null qos-id convention

- linux/net/rina/rds/robjects.c
- internal kobjects were not released due to missing call to decrement ref count
- string name passed to internal kobject functions was not being freed
maintainer: @vmaffione
> Pristine 1.5 fix several memory leaks in robjects

- linux/net/rina/rmt.c
add clean up of n1port when the binding operation fails due to wrong RMT's
policy set installed.
This was causing a big kernel dump when trying a second time because a kobject with the same name was already there
maintainer @miqueltarzan
> kernel:rmt: fix missing clean up of n1port

- rinad/src/ipcm/ipcm.cc
After a read that target a SHIM, the SHIM was returning an
IPCM_ERROR (it doesn't implement the read) but was not releasing
the lock, which produced a deadlock when trying to registrate
an ipcp to the mentioned SHIM
Fixes #945 
ack @edugrasa
> SHIM delegated did not release the lock

- librina/wrap/librina.i
If exceptions are not explicetly declared in the .h function
declaration, SWIG does not wrap them and hence, they can not be
catched in java. To avoid the problem without changing the .h,
it is possible to define the catch in the .i.
This commit wraps all the catches thrown by functions in
librina/ipc-api.h
Fixes #947 
ack @edugrasa
> Added java catch for exceptions thrown in ipc-api

- librina/src/ipc-api.cc
- librina/wrap/c/src/librina-c.cc
Returning 0 when there is no packet makes the C API think there is a packet with 0 length. When reading in a non-blocking way to loop over port_id's in a select() kind of way, makes the application think there is always a 0-length packet on that port_id.
This should fix ioq3 to work with multiple clients.
> fix in ipc-api.

- librina/src/rib_v2.cc
Delegation objects were not arriving to the amnager with its full
name, but with the rleative name of the ipcp. Now the MA completes
the delegated object name with the Ma relative path, creating the
complete fqn of the object
Fixes #954 
ack @edugrasa
> Name of delegation objects completed

- rinad/src/ipcm/flow-alloc-handlers.cc
The previous logic was wrong, since a DIF specified explicitely from
the user could be overwritten by the DIF allocator.
> rinad: ipcm: flow_allocation_requested_local: fix DIF selection logic

- rina-tools/src/common/Makefile.am
- rina-tools/src/common/application.cc
- rina-tools/src/common/server.cc
- rina-tools/src/common/server.h
- rina-tools/src/common/utils.cc
- rina-tools/src/common/utils.h
- rina-tools/src/manager/main.cc
- rina-tools/src/manager/manager.cc
- rina-tools/src/manager/manager.h
- rina-tools/src/rina-cdap-echo/cdap-echo-client.cc
- rina-tools/src/rina-cdap-echo/cdap-echo-client.h
- rina-tools/src/rina-cdap-echo/cdap-echo-server.cc
- rina-tools/src/rina-cdap-echo/cdap-echo-server.h
- rina-tools/src/rina-cdap-echo/main.cc
- rina-tools/src/rina-echo-time/et-client.cc
- rina-tools/src/rina-echo-time/et-client.h
- rina-tools/src/rina-echo-time/et-server.cc
- rina-tools/src/rina-echo-time/et-server.h
- rina-tools/src/rina-echo-time/main.cc
Using the "-d" option, it is possible to specify multiple DIF names separated by ";"
./rina-echo-time -l -d "normal.DIF;vpn.DIF;test.DIF"
@vmaffione could you give it a go?
> rina-tools: allow servers to register to multiple DIFs

- linux/net/rina/dtcp-ps-default.c
- linux/net/rina/dtp.c
- linux/net/rina/dtp.h
The handler of the A-timer expiration event did not take into account
that the PCI being handed in to the DTCP could have been already
deallocated by the EFCP. Now a duplicated PCI is used.
maintainers: @lbergesio
> kernel: dtp: Fix bug in dtp

- linux/net/rina/efcp.c
- linux/net/rina/ipcps/normal-ipcp.c
- linux/net/rina/ipcps/shim-eth-vlan-core.c
- linux/net/rina/ipcps/shim-hv-core.c
- linux/net/rina/ipcps/shim-tcp-udp.c
- linux/net/rina/rmt.c
- linux/net/rina/sdup.c
Fixed bug when destroying IPCP that is using 1 or more N-1 flows. Fixes #964 
@miqueltarzan, @vmaffione could you check you agree with modifications? Tests show the bugs are gone (Bug reported in 964 was hiding another related bug that is fixed by this PR)
> kernel: normal, rmt, efcp, sdup, shims: fixed bug when destroying IPCPs

- linux/net/rina/dt-utils.c
- linux/net/rina/dt.c
- linux/net/rina/dtcp.c
- linux/net/rina/dtp.c
- linux/net/rina/efcp.c
- linux/net/rina/ipcps/normal-ipcp.c
- linux/net/rina/ipcps/shim-eth-vlan-core.c
- linux/net/rina/ipcps/shim-tcp-udp.c
- linux/net/rina/kfa.c
- linux/net/rina/pff-ps-default.c
- linux/net/rina/rinarp/arp826-tables.c
- linux/net/rina/rmt.c
This commit is actually a backport from Arcfire needed to fix a bad behaviour in EFCP.
spin_lock_irqsave/irqrestore has been replaced in all the kernel code by spin_lock_bh. In this way HW interrupts are NOT disabled and the NIC can still receive packets from the wire and allocate them in its buffer, while bottom halves (soft IRQs including  net_rx_softirq) are properly disabled.
99% of changes are these replacements. Nevertheless KFA has a sensitive change by removing present IRQ_BARRIER s, although they should not be needed anymore it deserves proper checking.
Mainteiners:
@sandervrijders 
linux/net/rina/ipcps/shim-eth-vlan-core.c
linux/net/rina/ipcps/shim-tcp-udp.c
linux/net/rina/pff-ps-default.c
linux/net/rina/rinarp/arp826-tables.c
@miqueltarzan 	linux/net/rina/ipcps/normal-ipcp.c …
> Replace spin_lock_irqsave per spin_lock_bh

- linux/net/rina/rmt.c
- linux/net/rina/sdup.c
This was causing RCU stalls due to unbounded RCU grace periods, which
in turn used to cause OOM.
Nothing really related to KVM or XEN.
Fixes #927 
Additional examples of stack dumps, obtained with simple rina-tgen tests between two machines, normal over shim scenario.
@edugrasa @miqueltarzan
````
[ 4666.436232] INFO: rcu_preempt detected stalls on CPUs/tasks: {} (detected by 0, t=18002 jiffies, g=21413, c=21412, q=805)
[ 4666.436285] All QSes seen, last rcu_preempt kthread activity 0 (4296277228-4296277228), jiffies_till_next_fqs=2, root ->qsmask 0x0
[ 4666.436285] ksoftirqd/0     R  running task        0     3      2 0x00000000
[ 4666.436285]  ffff880006d21420 000000005da6fbef ffff880007a03d88 ffffffff810a51a1
[ 4666.436285]  ffff880007a16e00 ffffffff8184ba80 ffff880007a03e18 …
```
> rmt, sdup: match unmatched RCU critical sections

- plugins/rdsr-ps/README
- plugins/rdsr-ps/cdrr/README
- plugins/rdsr-ps/cdrr/dtcp-ps-cdrr.c
- plugins/rdsr-ps/ecn/Makefile
- plugins/rdsr-ps/ecn/rmt-ps-ecn.c
- plugins/rdsr-ps/fare/Makefile
- plugins/rdsr-ps/fare/fa-ps-fare.cpp
- plugins/rdsr-ps/pffb/Makefile
- plugins/rdsr-ps/pffb/README
- plugins/rdsr-ps/pffb/pff-ps-pffb.c
- plugins/rdsr-ps/pffb/pffb.manifest
These are the last version of Create-Net policies for CC and custom forwarding strategies that are currently in use to generate the deliverable 6.x final experiments results.
The policies has been tested on some lightly different branch (https://github.com/kewinrausch/stack/tree/pristine-1.5-os and https://github.com/kewinrausch/stack/commits/pristine-1.5-dms), but since they are abstracted thanks on the kernel SDK, no conflicts has been detected until now.
> plugins: rdsr : Merged the last version of the policies

- linux/net/rina/rds/ringq.c
DEBUG message had a wrong pointer, now fixed
> kernel:rds:ringq fix debug msg

- librina/include/librina/rib_v2.h
- librina/src/rib_v2.cc
- rinad/src/ipcm/addons/console.cc
- rinad/src/ipcm/ipcm.cc
- rinad/src/ipcm/ipcm.h
- rinad/src/ipcm/misc-handlers.cc
- rinad/src/ipcp/ipc-process.cc
- rinad/src/ipcp/rib-daemon.cc
The netlink message already carried objectClass/objectName fields, but they were neither filled nor processed. 2 things in particular about the implementation:
- If *objectName* does not end with `/`, then *query-rib* returns information for this exact object. Otherwise, it also returns all information from child objects.
- Since the console does not provide any escaping mechanism that could be used to pass an empty token, `-` can be passed to *class* if one only wants to only filter by *name*.
> query-rib: filtering by object class/name

- librina/src/ipc-manager.cc
- rinad/src/ipcm/main.cc
The second commit is a workaround. A full solution may be:
- make the SIGCHLD handler record somewhere which zombie was reaped
- temporary block the SIGCHLD handler around kill(), and only kill if not reaped
Another one may be to stop using signal handler for that.
> IPCM: fix issues with SIGCHLD handling

- rinad/src/ipcm/addons/console.cc
- rinad/src/ipcm/addons/console.h
Writes (responses to clients) are not asynchronous, which means that a client can block the console if it does not read responses. But the buffer is quite big so that's good enough for the moment.
> IPCM console: accept multiple simultaneous connections

- rina-tools/src/rina-echo-time/et-client.cc
- Timeouts were reported as 'bad response'.
- Late pongs (i.e. not lost, which can happen when testing over shim tcp)
were also reported as 'bad response', except for a few specific SDU sizes.
There remains 1 issue that I explained in a comment:
> TODO: Always read SDUs while waiting before the next ping. Otherwise, any late and bad response would flush 'sent' and we'd have no way anymore to check correctly the following responses. This is a rare scenario and for now, readSDU can't do that without using all CPU, which we want to avoid.
Do you know if `IPCManager::readSDU` returns `-EINTR` when a signal is processed ? In `Client::readSDU`, I could use replace the busy loop by something using `setitimer`.
The following output is a test over shim tcp, and firewall rules to temporarily drop …
> rina-echo-time: fix processing of late pongs

- rina-tools/src/common/utils.cc
- rinad/src/ipcm/addons/ma/ribs/ipcp_obj.cc
This patch fixes a bug that was causing an OOM crash in parse_dif_names(),
when the second argument was an empty string. OOM was due to the
condition (pos == std::string::npos) failing due to type mismatch,
even if it was expected to succeed.
@edugrasa
> rina-tools, rinad: use size_t for string::find() result

- linux/net/rina/rmt-ps-default.c
This avois a possible kernel crash if "data" variable is NULL. It was also triggering a compiler warning.
> kernel: rmt-ps-default: fix broken indentation

- linux/net/rina/ipcp-instances.h
- linux/net/rina/ipcps/normal-ipcp.c
- linux/net/rina/ipcps/shim-eth-vlan-core.c
- linux/net/rina/ipcps/shim-hv-core.c
- linux/net/rina/ipcps/shim-tcp-udp.c
- linux/net/rina/kipcm.c
- linux/net/rina/pff-ps-default.c
- linux/net/rina/pff-ps-default.h
- linux/net/rina/pff-ps.h
- linux/net/rina/pff.c
- linux/net/rina/pff.h
- linux/net/rina/rmt.c
- linux/net/rina/rmt.h
- plugins/lfa/ps.c
- plugins/multipath/pff-ps-multipath.c
Fixed locking in PFF policy implementations (default and multipath), as it is right now there can be soft lockups if the RMT queries pff->nhop while the pff is being updated.
Also added a pff_modify atomic operation, that updates all the entries in the PFF without releasing the PFF lock. As it is done right now, first all the PFF entries are removed, then lock released, then for each entry get lock, add entry and release lock. If a PDU queries the next hop in any intermediary step (getting the lock), it may be dropped because the PFF entry is still not there.
Maintainers: @sandervrijders, @vmaffione
> Pristine 1.5 pff: fix locking and atomic modify

- rina-tools/src/rina-echo-time/et-client.cc
The operation removed is not needed, because it is performed anyway by the Client constructor.
It also causes a memory leak, since nobody frees tmp.
@miqueltarzan @edugrasa
> rina-echo-time: remove memory leak

- librina/src/ipc-api.cc
- linux/net/rina/kfa.c
- rina-tools/src/rina-echo-time/et-client.cc
This implements what I suggested in #1003, waiting that SDU can be read/written with posix API (like select).
This was quick enough to do, and the use of all CPU annoyed me too much, in particular in VMs.
> rina-echo-time: do not use all CPU while reading a SDU with a timeout

- rinad/src/ipcp/enrollment-task.cc
- rinad/src/ipcp/enrollment-task.h
@jmuchemb could you give it a try? I've tested the case when the member IPCP doesn't know the address of the IPCP that joins (in enrollment) and works for me
> rinad: fix segfault when enrollment fails, fix #872

- rinad/src/ipcp/plugins/default/routing-ps.cc
- rinad/src/ipcp/plugins/default/routing-ps.h
So that they are not too large to be sent through the N-1 DIF. This is a workaround until fragmentation/reassembly is implemented.
> Pristine 1.5: partition FlowStateObject update in different messages

- librina/test/test-rib_v2.cc
This fixes:
```
g++ -DHAVE_CONFIG_H -I. -I../src  -I../include -I/usr/include/libnl3  -I/usr/include/libnl3   -I../src -D_FORTIFY_SOURCE=2 -Wall -Wformat -Wnon-virtual-dtor -Woverloaded-virtual -Werror -Wfatal-errors -Wno-unused-variable -Wno-unused-parameter -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -c -o test_rib_v2-test-rib_v2.o `test -f 'test-rib_v2.cc' || echo './'`test-rib_v2.cc
In file included from ../include/librina/irm.h:29:0,
from ../include/librina/enrollment.h:30,
from ../include/librina/ipc-process.h:34,
from test-rib_v2.cc:30:
../include/librina/rib_v2.h:486:15: error: 'virtual void rina::rib::DelegationObj::forward_object(const con_handle_t&, rina::cdap::CDAPMessage::Opcode, std::string, std::string, const ser_obj_t&, const flags_t&, const …
```
> librina: fixed tests

- plugins/dctcp/Makefile
- plugins/dctcp/README.md
- plugins/dctcp/dctcp-plugin-ps.c
- plugins/dctcp/dctcp-plugin.manifest
- plugins/dctcp/dtcp-ps-dctcp.c
- plugins/dctcp/rmt-ps-dctcp.c
Data Center policies for RMT and DTCP. These policies mimic the DCTCP behavior described in DCTCP paper in IRATI. Resolves #862
> Data Center TCP-like policy

- librina/src/concurrency.cc
- librina/src/core.cc
- librina/src/timer.cc
- rina-tools/src/cdapc/unittests.cc
- rinad/src/ipcm/addons/console.cc
- rinad/src/ipcm/dif-template-manager.cc
- rinad/src/ipcp/enrollment-task.cc
- rinad/src/ipcp/ipc-process.cc
- rinad/src/ipcp/rib-daemon.cc
using install-user-from-scratch fails in rina-tools/src/cadapc because the resulting binary unittests does not have the --version argument.
This pull request solves #1033
> Pristine 1.5 Solve #1033

- rina-tools/src/cdapc/dmsworker.cc
- rinad/src/ipcp/enrollment-task.cc
Preventing a segfault when the Manager sends a CREATE CDAP operation on the neighbors RIB object of an IPCP.
> rinad: fixed bug in Neighbors RIB object

- rinad/src/ipcp/ipc-process.cc
- rinad/src/ipcp/ipc-process.h
- rinad/src/ipcp/normal-ipc-process.cc
class KernelSyncTrigger moved to ipc-process.h and modified to accept an
AbstractIPCProcessImpl* so it can be used by different implementations of IPCP
daemons.
> rinad:Move KernelSyncTrigger to ipc-process.h

- librina/src/ipc-api.cc
Simple fix required to build with buildroot
> librina: ipc-api: fix include for ioctl()

- librina/src/common.cc
- librina/src/core.cc
- librina/src/core.h
- librina/src/ipc-api.cc
- linux/net/rina/common.h
- linux/net/rina/iodev.c
- linux/net/rina/kfa.c
- linux/net/rina/kfa.h
- linux/net/rina/logs.h
This patch adds the necessary mechanism to implement selective wake up on poll()/select()/epoll() userspace callers with POLLIN events.
When a packet is received on the flow (or the flow is deallocated), the poll()er is waken up so that it can react to the event.
This depends on (and includes) #1054
> Add receive-side poll() kernel support

- librina/src/common.cc
- librina/src/core.cc
- librina/src/core.h
- librina/src/ipc-api.cc
ipcManager->getControlFd() used to return the netlink socket file descriptor. However, the netlink socket() is already read by the netlink reader, which implements a select() event loop. This makes impossible to let application select()/poll() on the netlink file descriptor.
This pull requests adds an eventfd to librina, associated to the events queue. Each time an event is pushed to the queue, a write() is done on the eventfd, and each time an event is popped from the queue, a read() is done on the eventfd. In this way the eventfd can be safely used by the application in its select()/poll() loop, without race conditions due to the concurrent select() loop of the netlink reader.
@edugrasa
> Use eventfd as a control device

- librina/src/core.cc
The race condition may happen since the thread that pops the event
tries to read from the eventfd before the thread that pushed the
event had the chance to write to the eventfd.
> librina: core: fix race condition on eventQueueReady

- rina-tools/src/common/application.cc
- rina-tools/src/rina-echo-time/et-client.cc
Use a large buffer for read().
This prevents error related to partial SDU read, which happens if packets larger than expected come on the flow.
@edugrasa
> rina-tools: use large read() in rina-echo-time client

- rina-tools/src/Makefile.am
- rina-tools/src/irati-ctl
Example:
````
Management Agent not started
Current IPC processes (id | name | type | state | Registered applications | Port-ids of flows provided)
1 | eth.1.IPCP:1:: | shim-eth-vlan | ASSIGNED TO DIF 300 | n1.1.IPCP-1-- | 1
2 | n1.1.IPCP:1:: | normal-ipc | ASSIGNED TO DIF n1.DIF | - | -
```
> Command line tool to access IPCM console

- librina/src/ipc-process.cc
- rinad/src/ipcp/components.h
- rinad/src/ipcp/plugins/default/Makefile.am
- rinad/src/ipcp/plugins/default/default.manifest
- rinad/src/ipcp/plugins/default/flow-allocator-ps.cc
- rinad/src/ipcp/plugins/default/plugin.cc
- rinad/src/ipcp/plugins/default/resource-allocator-ps.cc
- rinad/src/ipcp/plugins/default/routing-ps.cc
- rinad/src/ipcp/plugins/default/routing-ps.h
- rinad/src/ipcp/plugins/default/static-routing-ps.cc
- rinad/src/ipcp/resource-allocator.cc
- rinad/src/ipcp/resource-allocator.h
Fix #1111 . Adds a static routing policy. Routing entries are specified in the config file, as parameters of the routing policy. Example:
````
"routingConfiguration" : {
"policySet" : {
"name" : "static",
"version" : "1",
"parameters" : [{
"name"  : "17",
"value" : "0-1-17"
}]
}
````
Each policy parameter is a routing table entry. The name of the parameter is the destination address, the value of the parameter has the format <qos_id>-<cost>-<next hop address>.
Installing routing and forwarding table entries can be queried from the IPCM console, using the "query-rib" command.
````
Name: /resalloc/nhopt; Class: NextHopTable; Instance: 11
Value: -
Name: /resalloc/nhopt/key=17-0-1-17; Class: NextHopTableEntry; Instance: 37
Value: Destination name: ; Addresses: 17; ; QoS-id: 0; Cost: 1; Next …
```
> Arcfire staticrouting

- librina/wrap/rina-api/include/rina/api.h
- librina/wrap/rina-api/src/rina-api.cc
This adds `rina_flow_mss_get` (currently not implemented on IRATI), and changes the name of `rina_flow_spec_unreliable()` to avoid ambiguity.
> Align RINA api

- common/serdes-utils.c
- include/irati/kernel-msg.h
- include/irati/kucommon.h
- kernel/iodev.c
- kernel/ipcp-instances.h
- kernel/ipcps/normal-ipcp.c
- kernel/ipcps/shim-eth-vlan-core.c
- kernel/ipcps/shim-hv-core.c
- kernel/ipcps/shim-tcp-udp.c
- kernel/kfa.c
- kernel/kfa.h
- kernel/kipcm.c
- kernel/kipcm.h
- kernel/rina-device.c
- kernel/rina-device.h
- librina/include/librina/common.h
- librina/include/librina/ipc-process.h
- librina/src/common.cc
- librina/src/ipc-process.cc
- librina/wrap/rina-api/src/rina-api.cc
- rina-tools/src/key-managers/km-common.cc
- rina-tools/src/rina-cdap-echo/cdap-echo-client.cc
- rina-tools/src/rina-echo-time/et-client.cc
- rinad/etc/default.dif
- rinad/src/common/encoder.cc
- rinad/src/common/encoders/QoSSpecification.proto
- rinad/src/ipcp/enrollment-task.cc
- rinad/src/ipcp/flow-allocator.cc
- tests/conf/default.dif
Implemented the msg_boundaries flag of the flow_spec, return -EMSGSIZE when msg boundaries are preserved and SDU is too large for underlying DIF.
> Msg boundaries

- README.md
- kernel/ipcp-factories.c
- kernel/ipcp-factories.h
- kernel/rds/robjects.c
- kernel/rds/robjects.h
Avoid using symbol that was not exported in kernel versions previous to 4.4. This allows IRATI to support standard Ubuntu 16.04 (which runs on a 4.4 kernel)
> Arcfire: support kernel 4.1 - 4.4

- .travis.yml
- configure
- rina-tools/configure.ac
- rinad/configure.ac
Finally got the IRATI stack to build on the Travis CI service. All is explained in the issue ticket](https://github.com/IRATI/stack/issues/1109).
This branch has the latest commits from the arcfire branch and gets a nice green tick mark beside it to show that the build passes.
The main point for review is that I had to remove the dependency on version 0.2.0 of librina in the configuration of [rinad](https://github.com/IRATI/stack/blob/1109-travis-ci/rinad/configure.ac#L117) and [rina-tools](https://github.com/IRATI/stack/blob/1109-travis-ci/rina-tools/configure.ac#L141). 
The system still checks that librina is there, but it does not check for a specific version. 
The reason, this check is not done, is due to the fact that librina uses …
> 1109 travis ci build

- index.html
The anchor link href for www.irati.eu uses a relative syntax, causing the browser to try to load "http://irati.github.io/stack/www.irati.eu" instead. Adding the protocol so the href is "http://www.irati.eu" should fix the issue.
> Add protocol to www.irati.eu href to load correctly

- kernel/ipcps/shim-eth-vlan-core.c
- plugins/qta_mux/README.md
- plugins/qta_mux/qta-mux.c
Improvements to qta-mux:
* Allow configuration of different cherish levels per urgency queue
* Add probabilistic dequeue (to prevent starvation of lower traffic classes)
Fix bug in vertical flow control in shim-eth-vlan
> qta-mux & bug fixes

- .travis.yml
As outlined in Issue #1246 this change helps with the Travis CI build particularly for Kernel version 4.15.
With this change the build now passes as can bee seen on [Travis CI build 337](https://travis-ci.org/IRATI/stack/builds/422514834)
> For Issue #1246 changing Travis CI build to include build dependancy

- kernel/dtcp.c
- kernel/dtp-utils.c
Set it to always 1 to avoid undesired PDU reordering issues
> E2ens: fix issues in closed window queue

- rinad/src/common/rina-configuration.cc
- rinad/src/common/rina-configuration.h
- rinad/src/ipcm/dif-validator.cc
- rinad/src/ipcm/ipcm.cc
- rinad/src/ipcp/plugins/default/namespace-manager-ps.cc
This fixes the limitation that currently the only address assignment policy
is static assignment.
> WIP: rinad: query an external daemon when a IPCP address can't be found

- kernel/Makefile.in
- kernel/kfa.c
- kernel/kfa.h
- kernel/kipcm.c
- kernel/rina-device.c
- kernel/rina-device.h
- librina/include/librina/common.h
- rinad/src/ipcm/Makefile.am
- rinad/src/ipcm/addons/console.cc
- rinad/src/ipcm/app-handlers.cc
- rinad/src/ipcm/flow-alloc-handlers.cc
- rinad/src/ipcm/ip-vpn-manager.cc
- rinad/src/ipcm/ip-vpn-manager.h
- rinad/src/ipcm/ipcm.cc
- rinad/src/ipcm/ipcm.h
Add IP over RINA capabilities via a dedicated RINA network device that exposes a flow, allowing the kernel to use it to forward IP packets with certain prefixes to their destination. 
Ported functionality from ARCFIRE branch, will have to be later updated to a more flexible model (allowing multiple IP prefixes to be forwarded through the same RINA flow).
> Ip over RINA via dedicated netwok device

- kernel/pci.c
The name suggests that rvous_last_csn_rcvd field should have length ctrl_seq_num_length?
> rvous_last_csn_rcvd field should have length ctrl_seq_num_length

- kernel/dtcp.c
- kernel/dtp.c
- kernel/du.c
- kernel/ipcps/normal-ipcp.c
- kernel/pci.c
- kernel/pci.h
The version and PDU flags fields did not seem to be initialised for the packets.
> Initialise version and PDU flags in packets

- plugins/dctcp/dtcp-ps-dctcp.c
- plugins/red/dtcp-ps-red.c
Shouldn't cwnd increased exponentially rather than linearly during slow_start phase?
> exponentially increase cwnd during SLOW_START phase

- kernel/dtcp.c
- kernel/dtp.c
- plugins/cong_avoidance/rmt-ps-cas.c
…mespec_sub.
This is done by directly subtracting and scaling the fields, which results in
simpler code.
Change difference computation in rmt-ps-cas.c to use a new internal function
timespec_sub_ns, which computes the time difference directly in ns.
> Change dtp.c, dtcp.c, rmt-ps-cas.c to quit using timespec_sub

- kernel/delim-ps-default.c
- kernel/ipcps/shim-tcp-udp.c
- librina/src/Makefile.am
- rinad/src/common/encoders/Makefile.am
- rinad/src/ipcm/app-handlers.cc
- rinad/src/ipcp/enrollment-task.cc
- rinad/src/ipcp/plugins/sm-cbac/Makefile.am
Fixes the following issues:
- Wrong caling sequence in kernel_getsockname (#1334)
- Function that didn't return a result on ipcm (#1333)
- Generated proto files not removed when doing make clean (#1332)
- Kernel compilation warning
- Enrollment was not using a reliable N-1 flow in some cases
> Several bug and warning fixes

- rina-tools/src/rlite/Makefile.am
Fix the Makefile.am to make sure libiporina.la is built as part of the build.
The branch fixing bug 1340 should be merged with this one because both PR fix IRATI on Raspbian.
> Fix a bug that prevented iporinad from building

- kernel/dtp-utils.c
- kernel/dtp.c
The timer are destroyed further down the cleanup routine but they can still be triggered after the RTX queue object is freed.
> Stop the timers before freeing the RTX queue

- kernel/cidm.c
This statement was obviously missing and I think this is what caused the last lock ups that I've seen. Before going trigger-happy about closing the associated bug, though, I think I'll use the module for a bit longer.
> Missing spin_unlock before return.

- rinad/src/common/rina-configuration.cc
- rinad/src/ipcm/main.cc
I've built a script which allows me to dynamically start and stop specific IPCM configurations. For this to work well, though, I had to modify the IPCM to allow some of it's configuration elements to be overridden on the command line. This obviously isn't going to change anything for people not wanting that feature.
> PR01 -- Allow some configuration elements to be overriden on the command line

- librina/src/cdap_v2.cc
- librina/src/irm.cc
- librina/src/security-manager.cc
- librina/src/tlshand-authp.cc
- rina-tools/src/key-managers/km-common.cc
There is another pending PR for this but it's likely to be outdated. This patch is what I needed to do to get rinad and rina-tools to compile.
> PR02 -- GRPC: GetByteSize is deprecated.

- rinad/src/ipcm/configuration.cc
This is a small change that makes it easy to configuration files to be moved across hosts. If the configuration file parser finds the system name is set to $hostname, it will just fill-in the local system hostname.
I would venture that this should be the default behaviour if system-name is not set to anything or missing.
> PR03 -- Make it so that "system-name" can be the local hostname

- kernel/rinarp/arp826-arm.c
This is a tiny thing that I forgot to do in the code that has been merged in IRATI previously. It should be an non-issue to merge it.
I've been seeing the error message "ARP resolver called on timed out request"
without realizing that it meant that something was quite wrong in the code. It
turns out that when an ARP reply was received, the value of "timed_out" was not
initialized, which meant proper replies got rejected on a regular basis. Enough
requests still went through as normal that I didn't realize something was wrong
before now.
> PR04 -- Initialize the 'timed_out' value to something

- kernel/ipcps/shim-eth-core.c
- kernel/kfa-utils.c
- kernel/kfa-utils.h
- kernel/kfa.c
- kernel/kfa.h
- kernel/kipcm.c
- kernel/pidm.c
- kernel/pidm.h
- kernel/rinarp/arp826-arm.c
- kernel/rinarp/arp826-rxtx.c
- kernel/rinarp/arp826-tables.c
- kernel/rinarp/arp826-utils.c
- kernel/rinarp/arp826-utils.h
- kernel/rinarp/arp826.h
- kernel/rinarp/rinarp.c
- kernel/rinarp/rinarp.h
This patch adds a timeouts to ARP requests sent through a network interface. The default timeout is somewhat arbitrarily set to 5000 milliseconds by can be manipulated using a debugfs handle.
I admit this is a fairly large set of changes which could (should) be broken down in several parts. In fact, I see a few patch there that could be their own PRs. I'm not going to touch this for now though as I would like someone else to look into this set of change before putting in anymore work in it.
This set of patch was meant to prevent a lockup within IRATI when it ran out of ports to allocate. Unfortunately, it does not fix all situations as I've encountered some more lockups and have not had the time to fix those. It did improve the stability of IRATI significantly while using it in the …
> PR05 -- Timeout ARP requests
